import { StyleSheet } from 'react-native';

import type { AppColors } from '../../modules/theme/ThemeContext';

const BRAND_BLUE = '#246BFE';

/** 캘린더 가져오기 화면의 정적 스타일 묶음을 생성합니다. */
export function createCalendarImportStylesPart1(
  colors: AppColors,
  isDark: boolean,
  brandTint: string,
) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: isDark ? '#0F1115' : '#F8F9FB',
      paddingHorizontal: 22,
    },
    topRow: {
      minHeight: 36,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    backButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.04)',
    },
    backButtonHidden: {
      opacity: 0,
    },
    scroll: {
      flex: 1,
    },
    curationProgress: {
      flex: 1,
      height: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    curationProgressSegment: {
      flex: 1,
      height: 4,
      borderRadius: 2,
      backgroundColor: isDark
        ? 'rgba(255,255,255,0.12)'
        : 'rgba(15,23,42,0.10)',
    },
    curationProgressSegmentActive: {
      backgroundColor: BRAND_BLUE,
    },
    content: {
      flexGrow: 1,
      justifyContent: 'flex-start',
      paddingTop: 36,
      paddingBottom: 28,
    },
    stepMotion: {
      width: '100%',
    },
    stepWrap: {
      gap: 14,
    },
    introWrap: {
      gap: 15,
      paddingBottom: 12,
    },
    introLogoWrap: {
      width: 68,
      height: 68,
      borderRadius: 20,
      overflow: 'hidden',
      backgroundColor: '#0A84FF',
      marginBottom: 12,
    },
    introLogoImage: {
      width: '100%',
      height: '100%',
    },
    completeLogo: {
      width: 68,
      height: 68,
      borderRadius: 20,
      backgroundColor: BRAND_BLUE,
      marginBottom: 10,
    },
    importResultSummary: {
      marginTop: 10,
      overflow: 'hidden',
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surface2,
    },
    importResultRow: {
      minHeight: 50,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    importResultRowDivider: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    importResultIcon: {
      width: 30,
      height: 30,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: brandTint,
    },
    importResultLabel: {
      flex: 1,
      minWidth: 0,
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '800',
    },
    importResultValue: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '900',
    },
    stepIcon: {
      width: 60,
      height: 60,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: brandTint,
      marginBottom: 8,
    },
    eyebrow: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '900',
    },
    title: {
      color: colors.textPrimary,
      fontSize: 30,
      lineHeight: 38,
      fontWeight: '900',
      letterSpacing: 0,
    },
    subtitle: {
      maxWidth: 310,
      color: colors.textSecondary,
      fontSize: 15,
      lineHeight: 23,
      fontWeight: '700',
    },
    introPointList: {
      gap: 10,
      marginTop: 8,
    },
    introPoint: {
      minHeight: 28,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    introPointText: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '800',
    },
    providerList: {
      gap: 10,
      marginTop: 6,
    },
    providerRow: {
      minHeight: 68,
      borderRadius: 17,
      paddingHorizontal: 14,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: isDark ? '#17191F' : '#FFFFFF',
      borderWidth: 1,
      borderColor: colors.border,
    },
    providerRowSelected: {
      borderColor: BRAND_BLUE,
      backgroundColor: brandTint,
    },
    providerIconWrap: {
      width: 38,
      height: 38,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.04)',
    },
    providerIconMuted: {
      opacity: 0.62,
    },
    providerCopy: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    providerTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      minWidth: 0,
    },
    providerTitle: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '900',
    },
    providerDescription: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '800',
    },
    providerBadge: {
      borderRadius: 9,
      paddingHorizontal: 7,
      paddingVertical: 3,
      backgroundColor: isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
    },
    providerBadgeText: {
      color: colors.textSecondary,
      fontSize: 10,
      fontWeight: '900',
    },
    providerCheck: {
      width: 25,
      height: 25,
      borderRadius: 7,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: isDark ? '#16181D' : '#FFFFFF',
    },
    providerCheckSelected: {
      backgroundColor: BRAND_BLUE,
      borderColor: BRAND_BLUE,
    },
    providerNotice: {
      minHeight: 46,
      borderRadius: 15,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.04)',
    },
    providerNoticeText: {
      flex: 1,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '800',
    },
    consentCard: {
      borderRadius: 18,
      overflow: 'hidden',
      backgroundColor: isDark ? '#17191F' : '#FFFFFF',
      borderWidth: 1,
      borderColor: colors.border,
    },
    consentAllRow: {
      minHeight: 70,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 11,
      backgroundColor: isDark ? 'rgba(255,255,255,0.035)' : 'rgba(0,0,0,0.018)',
    },
    consentCheck: {
      width: 27,
      height: 27,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: isDark ? '#14161B' : '#FFFFFF',
    },
    consentCheckCompact: {
      width: 22,
      height: 22,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.4,
      borderColor: colors.border,
      backgroundColor: isDark ? '#14161B' : '#FFFFFF',
    },
    consentCheckSelected: {
      borderColor: BRAND_BLUE,
      backgroundColor: BRAND_BLUE,
    },
    consentCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    consentAllTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      lineHeight: 20,
      fontWeight: '900',
    },
    consentItemList: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    consentItem: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: isDark ? 'rgba(255,255,255,0.065)' : 'rgba(0,0,0,0.055)',
    },
    consentItemHeader: {
      minHeight: 62,
      flexDirection: 'row',
      alignItems: 'stretch',
    },
    consentItemToggle: {
      flex: 1,
      minWidth: 0,
      paddingLeft: 14,
      paddingRight: 6,
      paddingVertical: 11,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    consentTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      minWidth: 0,
    },
    consentItemTitle: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '900',
    },
    consentRequired: {
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '900',
    },
  });
}
