import { StyleSheet } from 'react-native';

import type { AppColors } from '../../modules/theme/ThemeContext';

const BRAND_BLUE = '#246BFE';

/** 캘린더 가져오기 화면의 정적 스타일 묶음을 생성합니다. */
export function createCalendarImportStylesPart2(
  colors: AppColors,
  isDark: boolean,
  brandTint: string,
) {
  return StyleSheet.create({
    consentDescription: {
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '800',
    },
    consentChevron: {
      width: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    consentDetailList: {
      gap: 7,
      paddingHorizontal: 16,
      paddingTop: 2,
      paddingBottom: 13,
      paddingLeft: 48,
    },
    consentDetailRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 6,
    },
    consentDetailBullet: {
      width: 7,
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 17,
      fontWeight: '900',
    },
    consentDetailText: {
      flex: 1,
      minWidth: 0,
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 17,
      fontWeight: '700',
    },
    inlineNotice: {
      borderRadius: 16,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 9,
      backgroundColor: colors.surface2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    inlineNoticeText: {
      flex: 1,
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '700',
    },
    scanList: {
      marginTop: 10,
      gap: 12,
    },
    scanRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    scanText: {
      fontSize: 14,
      fontWeight: '800',
    },
    emptyBox: {
      minHeight: 174,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: colors.surface2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      padding: 18,
    },
    emptyTitle: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '900',
    },
    emptyText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '700',
      textAlign: 'center',
    },
    selectionSummaryRow: {
      minHeight: 64,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 11,
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    selectionSummaryRowSelected: {
      borderColor: BRAND_BLUE,
      backgroundColor: brandTint,
    },
    selectionSummaryCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    selectionSummaryTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '900',
    },
    selectionSummaryDescription: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '800',
    },
    selectionSummaryAction: {
      flexShrink: 0,
      color: BRAND_BLUE,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '900',
    },
    sourceGroupList: {
      gap: 8,
    },
    sourceGroupButton: {
      minHeight: 54,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 9,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sourceGroupDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    sourceGroupCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    sourceGroupText: {
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '900',
    },
    sourceGroupCount: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '800',
    },
    individualScheduleDisclosure: {
      minHeight: 60,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 9,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.surface2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    individualScheduleDisclosureIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: brandTint,
    },
    individualScheduleDisclosureCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    individualScheduleDisclosureTitle: {
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '900',
    },
    individualScheduleDisclosureDescription: {
      color: colors.textSecondary,
      fontSize: 10,
      lineHeight: 14,
      fontWeight: '800',
    },
    individualScheduleDisclosureCount: {
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '900',
    },
    candidateList: {
      gap: 10,
    },
    candidateRow: {
      minHeight: 76,
      borderRadius: 14,
      padding: 12,
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    candidateRowSelected: {
      borderColor: BRAND_BLUE,
      backgroundColor: brandTint,
    },
    candidateRowReview: {
      backgroundColor: isDark
        ? 'rgba(255,255,255,0.045)'
        : 'rgba(255,255,255,0.72)',
    },
    checkCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: isDark ? '#16181D' : '#FFFFFF',
    },
    checkCircleSelected: {
      backgroundColor: BRAND_BLUE,
      borderColor: BRAND_BLUE,
    },
    candidateBody: {
      flex: 1,
      minWidth: 0,
      gap: 5,
    },
    candidateTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minWidth: 0,
    },
    candidateTitle: {
      flex: 1,
      minWidth: 0,
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '900',
    },
    candidateMeta: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '800',
    },
    calendarSourceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    calendarSourceDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
    },
    calendarSourceText: {
      flex: 1,
      minWidth: 0,
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: '800',
    },
    sectionTitle: {
      marginTop: 8,
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '900',
    },
    sectionDescription: {
      marginTop: -8,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '700',
    },
    categoryDefaultHeader: {
      marginTop: -2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    categoryDefaultTitle: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '900',
    },
    categoryDefaultHint: {
      flexShrink: 1,
      color: colors.textSecondary,
      textAlign: 'right',
      fontSize: 10,
      lineHeight: 14,
      fontWeight: '800',
    },
    categoryAssignmentSection: {
      gap: 8,
      marginTop: 2,
    },
    categoryAssignmentDisclosure: {
      minHeight: 64,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surface2,
    },
    categoryAssignmentDisclosureIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: brandTint,
    },
    categoryAssignmentDisclosureCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    categoryAssignmentDisclosureTitle: {
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '900',
    },
  });
}
