import { StyleSheet } from "react-native";

/** NotificationSettingsCard 화면의 정적 시각 규칙입니다. 화면 로직과 독립적으로 조정할 수 있도록 분리했습니다. */
const styles = StyleSheet.create({
    container: {
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 16,
        padding: 16,
        marginBottom: 14,
    },
    flatContainer: {
        borderWidth: 0,
        borderRadius: 0,
        padding: 0,
        marginBottom: 14,
        backgroundColor: "transparent",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        minHeight: 38,
    },
    flatHeader: {
        minHeight: 44,
        borderBottomWidth: 0,
        paddingHorizontal: 0,
        paddingBottom: 6,
    },
    headerText: { flex: 1, paddingRight: 12 },
    title: { fontSize: 15, lineHeight: 20, fontWeight: "700" },
    usage: { marginTop: 3, fontSize: 11.5, lineHeight: 16, fontWeight: "600" },
    compactSwitch: {
        transform: [{ scaleX: 0.88 }, { scaleY: 0.88 }],
    },
    notice: { marginTop: 10, fontSize: 12 },
    settings: { marginTop: 8 },
    label: { marginBottom: 7, fontSize: 12, fontWeight: "600" },
    description: { fontSize: 11, lineHeight: 16, fontWeight: "600" },
    modeSection: {
        marginTop: 16,
        paddingTop: 14,
        borderTopWidth: StyleSheet.hairlineWidth,
    },
    flatModeSection: {
        marginTop: 22,
        paddingTop: 0,
        borderTopWidth: 0,
    },
    flatSummaryCard: {
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 16,
        overflow: "hidden",
    },
    flatSummaryMain: {
        minHeight: 82,
        paddingHorizontal: 13,
        paddingVertical: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    flatSummaryCopy: {
        flex: 1,
        minWidth: 0,
    },
    flatSummaryLabel: {
        fontSize: 11,
        lineHeight: 15,
        fontWeight: "600",
    },
    flatSummaryTime: {
        marginTop: 2,
        fontSize: 21,
        lineHeight: 27,
        fontWeight: "800",
        fontVariant: ["tabular-nums"],
    },
    flatSummaryArrival: {
        marginTop: 2,
        fontSize: 11,
        lineHeight: 15,
        fontWeight: "500",
    },
    flatDurationPill: {
        minHeight: 28,
        borderRadius: 999,
        paddingHorizontal: 9,
        alignItems: "center",
        justifyContent: "center",
    },
    flatDurationText: {
        fontSize: 10.5,
        lineHeight: 15,
        fontWeight: "700",
    },
    flatSummaryDivider: {
        height: StyleSheet.hairlineWidth,
        marginHorizontal: 13,
    },
    flatModeControl: {
        minHeight: 40,
        margin: 8,
        borderRadius: 10,
        padding: 2,
        flexDirection: "row",
        alignItems: "stretch",
        gap: 3,
    },
    compactModeButton: {
        flex: 1,
        minWidth: 0,
        minHeight: 36,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
    },
    compactModeButtonSelected: {
        shadowColor: "#000000",
        shadowOpacity: 0.06,
        shadowRadius: 2,
        shadowOffset: { width: 0, height: 1 },
        elevation: 1,
    },
    compactModeText: {
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "700",
    },
    flatModePicker: {
        borderWidth: 1,
        borderRadius: 16,
        overflow: "hidden",
    },
    flatModeSummary: {
        minHeight: 82,
        paddingHorizontal: 13,
        paddingVertical: 11,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    flatModeSummaryIcon: {
        width: 38,
        height: 38,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    flatModeSummaryCopy: {
        flex: 1,
        minWidth: 0,
    },
    flatModeSummaryLabel: {
        marginBottom: 2,
        fontSize: 10.5,
        lineHeight: 14,
        fontWeight: "700",
    },
    flatModeSummaryValue: {
        fontSize: 14,
        lineHeight: 19,
        fontWeight: "800",
    },
    flatModeSummaryDescription: {
        marginTop: 4,
        fontSize: 11,
        lineHeight: 16,
        fontWeight: "600",
    },
    flatModeOptions: {
        borderTopWidth: StyleSheet.hairlineWidth,
    },
    flatModeOption: {
        minHeight: 66,
        paddingHorizontal: 13,
        paddingVertical: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    flatModeOptionIcon: {
        width: 32,
        height: 32,
        alignItems: "center",
        justifyContent: "center",
    },
    flatModeOptionCopy: {
        flex: 1,
        minWidth: 0,
    },
    flatModeOptionTitle: {
        fontSize: 13.5,
        lineHeight: 18,
        fontWeight: "800",
    },
    flatModeOptionDescription: {
        marginTop: 2,
        fontSize: 10.5,
        lineHeight: 15,
        fontWeight: "600",
    },
    flatModeDivider: {
        height: StyleSheet.hairlineWidth,
        marginLeft: 55,
    },
    pressedRow: {
        opacity: 0.68,
    },
    modeHeading: {
        marginBottom: 10,
    },
    modeHeadingTitle: {
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "800",
    },
    modeRow: {
        borderWidth: 1,
        borderRadius: 16,
        overflow: "hidden",
    },
    modeButton: {
        minHeight: 76,
        paddingHorizontal: 14,
        paddingVertical: 11,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    modeIcon: {
        width: 36,
        height: 36,
        borderRadius: 11,
        alignItems: "center",
        justifyContent: "center",
    },
    modeCopy: {
        flex: 1,
        minWidth: 0,
    },
    modeTitleRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    modeTitle: {
        fontSize: 14,
        lineHeight: 19,
        fontWeight: "800",
    },
    modeDescription: {
        marginTop: 3,
        fontSize: 11.5,
        lineHeight: 17,
        fontWeight: "600",
    },
    modeFootnote: {
        minHeight: 38,
        paddingHorizontal: 4,
        paddingTop: 10,
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 7,
    },
    modeFootnoteText: {
        flex: 1,
        fontSize: 11,
        lineHeight: 16,
        fontWeight: "600",
    },
    pushActionPanel: {
        borderWidth: 1,
        borderRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 11,
        marginBottom: 12,
    },
    flatPushOutcome: {
        minHeight: 42,
        marginTop: 10,
        marginBottom: 2,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 9,
        flexDirection: "row",
        alignItems: "center",
        gap: 7,
    },
    flatPushOutcomeText: {
        flex: 1,
        fontSize: 11.5,
        lineHeight: 17,
        fontWeight: "700",
    },
    pushActionHeading: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    pushActionTitle: {
        fontSize: 11.5,
        lineHeight: 16,
        fontWeight: "800",
    },
    pushActionList: {
        marginTop: 8,
        gap: 6,
    },
    pushActionItem: {
        minHeight: 23,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    pushActionLabel: {
        width: 62,
        fontSize: 10.5,
        fontWeight: "700",
    },
    pushActionValue: {
        flex: 1,
        fontSize: 10.5,
        fontWeight: "800",
    },
    alarmPanel: {
        borderWidth: 1,
        borderRadius: 14,
        padding: 13,
        marginBottom: 12,
    },
    flatAlarmPanel: {
        borderWidth: 0,
        borderRadius: 0,
        paddingHorizontal: 0,
        paddingTop: 6,
        paddingBottom: 0,
    },
    flatAlarmIssueRow: {
        minHeight: 68,
        borderRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    notificationIssueRow: {
        marginTop: 10,
    },
    flatAlarmIssueIcon: {
        width: 34,
        height: 34,
        borderRadius: 11,
        alignItems: "center",
        justifyContent: "center",
    },
    flatAlarmIssueCopy: {
        flex: 1,
        minWidth: 0,
    },
    flatAlarmIssueTitle: {
        fontSize: 12.5,
        lineHeight: 18,
        fontWeight: "800",
    },
    flatAlarmIssueDescription: {
        marginTop: 2,
        fontSize: 10.5,
        lineHeight: 15,
        fontWeight: "600",
    },
    flatAlarmIssueAction: {
        minHeight: 44,
        paddingHorizontal: 4,
        justifyContent: "center",
    },
    flatAlarmIssueActionText: {
        fontSize: 11,
        lineHeight: 16,
        fontWeight: "800",
    },
    alarmPanelHeader: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 10,
    },
    alarmPanelCopy: {
        flex: 1,
    },
    alarmStatusTitle: {
        fontSize: 13,
        fontWeight: "800",
    },
    alarmStatusDescription: {
        marginTop: 4,
        fontSize: 11,
        lineHeight: 16,
        fontWeight: "600",
    },
    compactButton: {
        minWidth: 64,
        borderWidth: 1,
        borderRadius: 999,
        paddingHorizontal: 9,
        paddingVertical: 5,
        alignItems: "center",
    },
    compactButtonText: {
        fontSize: 10,
        fontWeight: "800",
    },
    permissionList: {
        marginTop: 10,
        gap: 6,
    },
    permissionRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    permissionLabel: {
        fontSize: 11,
        fontWeight: "600",
    },
    permissionValue: {
        fontSize: 11,
        fontWeight: "800",
    },
    actionRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        marginTop: 11,
    },
    actionButton: {
        borderWidth: 1,
        borderRadius: 999,
        paddingHorizontal: 11,
        paddingVertical: 7,
    },
    actionButtonText: {
        fontSize: 11,
        fontWeight: "800",
    },
    testButton: {
        marginTop: 11,
        minHeight: 44,
        borderWidth: 1,
        borderRadius: 11,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 12,
    },
    testButtonText: {
        fontSize: 12,
        fontWeight: "800",
    },
    flatTestRow: {
        minHeight: 56,
        marginTop: 4,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    flatTestIcon: {
        width: 36,
        height: 36,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    flatTestCopy: {
        flex: 1,
        minWidth: 0,
    },
    flatTestTitle: {
        fontSize: 14,
        lineHeight: 19,
        fontWeight: "700",
    },
    flatTestDescription: {
        marginTop: 2,
        fontSize: 11.5,
        lineHeight: 16,
        fontWeight: "500",
    },
    testHelperRow: {
        marginTop: 8,
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 5,
    },
    testHelperText: {
        flex: 1,
        fontSize: 10,
        lineHeight: 14,
        fontWeight: "600",
    },
    disabledButton: {
        opacity: 0.45,
    },
    feedback: {
        marginTop: 9,
        fontSize: 11,
        lineHeight: 16,
        fontWeight: "600",
    },
    recommendationCard: {
        borderWidth: 1,
        borderRadius: 14,
        padding: 13,
        flexDirection: "row",
        gap: 14,
    },
    flatRecommendationCard: {
        borderWidth: 0,
        borderRadius: 0,
        padding: 0,
        gap: 10,
        backgroundColor: "transparent",
    },
    recommendationCol: {
        flex: 1,
    },
    flatRecommendationField: {
        minHeight: 76,
        borderWidth: 1,
        borderRadius: 16,
        paddingHorizontal: 13,
        paddingVertical: 11,
        justifyContent: "center",
    },
    recommendationValue: {
        fontSize: 17,
        lineHeight: 22,
        fontWeight: "800",
    },
    recommendationDivider: {
        width: StyleSheet.hairlineWidth,
    },
    reminderMetaRow: {
        marginTop: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 10,
    },
    reminderMetaText: {
        flex: 1,
        minWidth: 0,
    },
    useButton: {
        minHeight: 44,
        borderWidth: 1,
        borderRadius: 999,
        paddingVertical: 6,
        paddingHorizontal: 10,
        justifyContent: "center",
    },
    useButtonText: {
        fontSize: 11,
        fontWeight: "800",
    },
});

export default styles;
