import { StyleSheet } from "react-native";

export type QuickScheduleLogoLoaderStylesOptions = {
    CENTER_X: number;
    CENTER_Y: number;
    LOGO_SIZE: number;
    STAGE_HEIGHT: number;
    STAGE_WIDTH: number;
};

/** 화면 레이아웃 상수를 주입받아 정적 스타일을 한 번 생성합니다. */
export function createQuickScheduleLogoLoaderStyles({
    CENTER_X,
    CENTER_Y,
    LOGO_SIZE,
    STAGE_HEIGHT,
    STAGE_WIDTH,
}: QuickScheduleLogoLoaderStylesOptions) {
    return StyleSheet.create({
    stage: {
        width: STAGE_WIDTH,
        height: STAGE_HEIGHT,
        alignSelf: "center",
        position: "relative",
        marginBottom: 2,
        overflow: "visible",
    },
    ambientHalo: {
        position: "absolute",
        left: CENTER_X - 34,
        top: CENTER_Y - 34,
        width: 68,
        height: 68,
        borderRadius: 34,
        shadowOffset: { width: 0, height: 0 },
    },
    orbitTrack: {
        position: "absolute",
        borderWidth: StyleSheet.hairlineWidth,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.28,
        shadowRadius: 7,
    },
    horizontalOrbit: {
        left: 8,
        top: 42,
        width: 178,
        height: 82,
        borderRadius: 89,
        transform: [{ rotate: "-7deg" }],
    },
    verticalOrbit: {
        left: 38,
        top: 6,
        width: 118,
        height: 154,
        borderRadius: 77,
        transform: [{ rotate: "24deg" }],
    },
    diagonalOrbit: {
        left: 17,
        top: 32,
        width: 160,
        height: 104,
        borderRadius: 80,
        transform: [{ rotate: "54deg" }],
    },
    logoFloatLayer: {
        position: "absolute",
        left: CENTER_X - LOGO_SIZE / 2,
        top: CENTER_Y - LOGO_SIZE / 2,
        width: LOGO_SIZE,
        height: LOGO_SIZE + 9,
        zIndex: 12,
    },
    logoDepthFar: {
        position: "absolute",
        left: 2,
        top: 7,
        width: LOGO_SIZE - 4,
        height: LOGO_SIZE,
        borderRadius: 25,
        borderWidth: StyleSheet.hairlineWidth,
        opacity: 0.72,
    },
    logoDepthNear: {
        position: "absolute",
        left: 1,
        top: 3.5,
        width: LOGO_SIZE - 2,
        height: LOGO_SIZE,
        borderRadius: 25,
        borderWidth: StyleSheet.hairlineWidth,
        opacity: 0.9,
    },
    logoStaticLayer: {
        position: "absolute",
        left: 0,
        top: 0,
        width: LOGO_SIZE,
        height: LOGO_SIZE,
        borderRadius: 25,
        zIndex: 3,
        elevation: 14,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 26,
    },
    logoImageMask: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 25,
        overflow: "hidden",
    },
    // 1024px 원본에서 중앙 유리 로고 영역만 84px 프레임에 맞춰 보여준다.
    calendarLogoImageCrop: {
        position: "absolute",
        left: -52,
        top: -49,
        width: 184,
        height: 184,
    },
    logoGlassTreatment: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 25,
        overflow: "hidden",
    },
    logoSheen: {
        position: "absolute",
        left: -12,
        top: -12,
        width: 76,
        height: 38,
        borderRadius: 24,
        transform: [{ rotate: "-10deg" }],
    },
    logoLowerBloom: {
        position: "absolute",
        right: -18,
        bottom: -24,
        width: 66,
        height: 58,
        borderRadius: 33,
    },
    logoTopEdge: {
        position: "absolute",
        left: 19,
        right: 19,
        top: 2,
        height: 1,
        borderRadius: 1,
    },
    logoEdge: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 25,
        borderWidth: StyleSheet.hairlineWidth,
    },
    particle: {
        position: "absolute",
        left: CENTER_X,
        top: CENTER_Y,
        alignItems: "center",
        justifyContent: "center",
        // 입자는 궤도 바깥에서는 보이지만 중앙 로고를 통과할 때는 로고 뒤로 숨는다.
        zIndex: 8,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.95,
        shadowRadius: 8,
    },
    horizontalParticle: {
        width: 8,
        height: 8,
        marginLeft: -4,
        marginTop: -4,
        borderRadius: 4,
    },
    verticalParticle: {
        width: 6,
        height: 6,
        marginLeft: -3,
        marginTop: -3,
        borderRadius: 3,
    },
    particleCore: {
        width: 4,
        height: 4,
        borderRadius: 2,
        backgroundColor: "#FFFFFF",
    },
    particleCoreSmall: {
        width: 3,
        height: 3,
        borderRadius: 1.5,
        backgroundColor: "#FFFFFF",
    },
    satelliteFrame: {
        position: "absolute",
        width: 42,
        height: 46,
        zIndex: 18,
        elevation: 10,
        shadowOffset: { width: 0, height: 7 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
    },
    satelliteDepth: {
        position: "absolute",
        left: 2,
        top: 4,
        width: 38,
        height: 40,
        borderRadius: 13,
        borderWidth: StyleSheet.hairlineWidth,
        opacity: 0.76,
    },
    satelliteTile: {
        width: 40,
        height: 40,
        borderRadius: 13,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
    },
    satelliteTopLeft: {
        left: 5,
        top: 38,
    },
    satelliteTopRight: {
        right: 7,
        top: 10,
    },
    satelliteBottomRight: {
        right: 10,
        bottom: 5,
    },
    satelliteInnerGlow: {
        ...StyleSheet.absoluteFillObject,
    },
    satelliteSheen: {
        position: "absolute",
        left: -6,
        top: -7,
        width: 42,
        height: 20,
        borderRadius: 13,
        transform: [{ rotate: "-10deg" }],
    },
    satelliteTopEdge: {
        position: "absolute",
        left: 10,
        right: 10,
        top: 1,
        height: StyleSheet.hairlineWidth,
        borderRadius: 1,
    },
});
}
