import { StyleSheet } from "react-native";

/** ScheduleAddModal 화면의 정적 시각 규칙입니다. 화면 로직과 독립적으로 조정할 수 있도록 분리했습니다. */
const styles = StyleSheet.create({
    wrapper:  {
        ...StyleSheet.absoluteFillObject,
        justifyContent: "flex-end",
        zIndex: 80,
        elevation: 80,
    },
    morphWrapper: {
        justifyContent: "flex-start",
    },
    prewarmHidden: {
        opacity: 0,
        zIndex: -1,
        elevation: 0,
    },
    dim:      { ...StyleSheet.absoluteFillObject },
    dimLight: { backgroundColor: "rgba(0,0,0,0.30)" },
    dimDark:  { backgroundColor: "rgba(0,0,0,0.58)" },
    sheetMotion: {
        width: "100%",
        maxHeight: "92%",
        paddingHorizontal: 14,
        paddingBottom: 10,
    },
    morphSheetMotion: {
        position: "absolute",
        overflow: "visible",
        transformOrigin: [0, 0, 0],
        shadowColor: "#000000",
        shadowOpacity: 0.16,
        shadowRadius: 22,
        shadowOffset: { width: 0, height: 10 },
        elevation: 16,
    },
    sheet: {
        maxHeight: "100%",
        borderRadius: 26,
        borderWidth: 1,
        overflow: "hidden",
        zIndex: 1,
    },
    morphSheet: {
        position: "relative",
        width: "100%",
        height: "100%",
        maxHeight: undefined,
        overflow: "visible",
    },
    morphDenseSurface: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 26,
        borderWidth: 1,
        overflow: "hidden",
        zIndex: 1,
    },
    sheetInnerContent: { maxHeight: "100%" },
    morphInnerContent: {
        flex: 1,
        transformOrigin: [0, 0, 0],
    },
    morphContentRevealCurtain: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 26,
        zIndex: 2,
    },
    morphBodyContent: {
        position: "relative",
    },
    handleWrap:    { alignItems: "center", paddingTop: 8, paddingBottom: 8 },
    handle:        { width: 36, height: 4, borderRadius: 2, opacity: 0.24 },
    scrollView: { maxHeight: "100%" },
    scrollContent: { paddingHorizontal: 20, paddingTop: 6, paddingBottom: 14 },
    morphScrollContent: { paddingTop: 14 },
    headerRow: {
        flexDirection: "row", alignItems: "center",
        justifyContent: "flex-end", minHeight: 36, marginBottom: 12,
    },
    headerTitleGroup: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    headerTitle:  { fontSize: 19, fontWeight: "700", letterSpacing: -0.25 },
    closeBtn: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: "center",
        justifyContent: "center",
    },
    previewCard: {
        borderWidth: 1,
        borderRadius: 18,
        minHeight: 116,
        marginBottom: 18,
        padding: 14,
        flexDirection: "row",
        gap: 12,
    },
    previewColorBar: {
        width: 5,
        borderRadius: 999,
        alignSelf: "stretch",
    },
    previewBody: {
        flex: 1,
        minWidth: 0,
    },
    previewTitle: {
        fontSize: 20,
        fontWeight: "600",
        letterSpacing: 0,
    },
    previewMeta: {
        marginTop: 4,
        fontSize: 13,
        fontWeight: "600",
    },
    previewChipRow: {
        marginTop: 10,
        flexDirection: "row",
        gap: 7,
    },
    previewChip: {
        minWidth: 0,
        maxWidth: "50%",
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 999,
        paddingHorizontal: 9,
        paddingVertical: 5,
        backgroundColor: "rgba(255,255,255,0.055)",
    },
    previewChipText: {
        fontSize: 11,
        fontWeight: "600",
    },
    previewSub: {
        marginTop: 10,
        fontSize: 12,
        fontWeight: "600",
    },
    label:        { marginBottom: 6, fontSize: 12, fontWeight: "600" },
    formError: {
        marginTop: -6,
        marginBottom: 12,
        fontSize: 12,
        fontWeight: "600",
    },
    titleInputWrap: {
        minHeight: 56,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        paddingLeft: 15,
        paddingRight: 12,
        marginBottom: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    titleInputWrapEmphasized: {
        borderWidth: 1,
    },
    titleInput: {
        flex: 1,
        minWidth: 0,
        paddingVertical: 14,
        fontSize: 16,
        fontWeight: "600",
    },
    categoryInlineChip: {
        maxWidth: 128,
        minHeight: 30,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 999,
        paddingHorizontal: 9,
        paddingVertical: 5,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    categoryInlineDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    categoryInlineText: {
        flexShrink: 1,
        fontSize: 12,
        fontWeight: "600",
    },
    categoryInlineChevron: {
        width: 13,
        height: 16,
        alignItems: "center",
        justifyContent: "center",
    },
    compactSectionCard: {
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        marginBottom: 12,
        overflow: "hidden",
    },
    compactToggleRow: {
        minHeight: 48,
        paddingHorizontal: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    compactDateTimeRow: {
        minHeight: 56,
        paddingLeft: 14,
        paddingRight: 10,
        flexDirection: "row",
        alignItems: "stretch",
        gap: 10,
    },
    compactDatePressable: {
        flex: 1,
        minWidth: 0,
        minHeight: 52,
        justifyContent: "center",
        paddingVertical: 6,
        borderRadius: 10,
    },
    compactValuePressable: {
        minHeight: 48,
        maxWidth: "52%",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: 3,
        paddingVertical: 6,
        borderRadius: 10,
    },
    compactRowTitle: {
        fontSize: 14,
        fontWeight: "600",
    },
    compactRowSub: {
        marginTop: 2,
        fontSize: 11,
        fontWeight: "600",
    },
    compactRowValue: {
        flexShrink: 1,
        fontSize: 15,
        fontWeight: "600",
        textAlign: "right",
    },
    compactValueCaption: {
        fontSize: 11,
        fontWeight: "600",
    },
    compactDivider: {
        height: StyleSheet.hairlineWidth,
        marginLeft: 14,
    },
    toggleSwitch: {
        alignSelf: "center",
        marginRight: -3,
        transform: [{ scale: 0.88 }],
    },
    memoCollapsedCard: {
        minHeight: 52,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        marginBottom: 12,
        paddingHorizontal: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    memoCollapsedText: {
        flex: 1,
        fontSize: 14,
        fontWeight: "600",
    },
    memoInputCard: {
        minHeight: 86,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        marginBottom: 12,
        overflow: "hidden",
    },
    memoTextInput: {
        minHeight: 84,
        paddingHorizontal: 14,
        paddingTop: 13,
        paddingBottom: 13,
        fontSize: 14,
        fontWeight: "500",
        textAlignVertical: "top",
    },
    pickerContainer: { borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, overflow: "hidden" },
    saveBtn: {
        height: 48, borderRadius: 14,
        alignItems: "center", justifyContent: "center",
        borderWidth: StyleSheet.hairlineWidth,
    },
    saveBtnText: { fontWeight: "700", fontSize: 15 },
});

export default styles;
