import { StyleSheet } from "react-native";

/** calendars 화면의 정적 시각 규칙입니다. 화면 로직과 독립적으로 조정할 수 있도록 분리했습니다. */
const styles = StyleSheet.create({
    root: { flex: 1 },
    header: { minHeight: 60, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    headerTitle: { fontSize: 18, fontWeight: "800", letterSpacing: 0 },
    iconButton: { width: 42, height: 42, borderRadius: 21, borderWidth: 1, borderColor: "transparent", alignItems: "center", justifyContent: "center" },
    content: { paddingHorizontal: 18, gap: 24 },
    section: { gap: 10 },
    sectionTitle: { fontSize: 16, fontWeight: "800", letterSpacing: 0 },
    inputRow: { height: 48, borderWidth: 1, borderRadius: 8, flexDirection: "row", alignItems: "center", paddingLeft: 13 },
    input: { flex: 1, minWidth: 0, height: "100%", paddingVertical: 0, fontSize: 15, fontWeight: "600", letterSpacing: 0 },
    addButton: { width: 42, height: 42, marginRight: 2, borderRadius: 7, alignItems: "center", justifyContent: "center" },
    inlineIconButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center" },
    colorRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    colorButton: { width: 36, height: 36, borderRadius: 18, borderWidth: 2, alignItems: "center", justifyContent: "center" },
    colorButtonSelected: { borderColor: "#2F80FF" },
    colorSwatch: { width: 24, height: 24, borderRadius: 12 },
    modeControl: { minHeight: 44, borderRadius: 8, padding: 3, flexDirection: "row", gap: 3 },
    modeOption: { flex: 1, minWidth: 0, borderWidth: 1, borderColor: "transparent", borderRadius: 6, paddingHorizontal: 8, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
    modeText: { flexShrink: 1, fontSize: 12, lineHeight: 15, fontWeight: "800", textAlign: "center", letterSpacing: 0 },
    loadingRow: { minHeight: 54, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
    empty: { minHeight: 84, borderTopWidth: 1, borderBottomWidth: 1, alignItems: "center", justifyContent: "center", gap: 6 },
    emptyText: { fontSize: 13, fontWeight: "600", letterSpacing: 0 },
    calendarRow: { minHeight: 64, borderWidth: 1, borderRadius: 8, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 11 },
    calendarMark: { width: 8, height: 32, borderRadius: 4 },
    rowText: { flex: 1, minWidth: 0 },
    rowTitle: { fontSize: 15, fontWeight: "800", letterSpacing: 0 },
    rowMeta: { marginTop: 2, fontSize: 12, lineHeight: 16, fontWeight: "600", letterSpacing: 0 },
    detailBand: { borderTopWidth: 1, paddingTop: 20, gap: 12 },
    detailLoading: { minHeight: 112, borderTopWidth: 1, paddingTop: 20, alignItems: "center", justifyContent: "center", gap: 10 },
    retryButton: { height: 36, borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 6 },
    retryText: { fontSize: 12, fontWeight: "800", letterSpacing: 0 },
    detailHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
    shareButton: { minWidth: 92, height: 38, borderRadius: 8, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
    shareButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800", letterSpacing: 0 },
    fieldLabel: { marginTop: 2, fontSize: 12, fontWeight: "700", letterSpacing: 0 },
    preferenceRow: { minHeight: 54, flexDirection: "row", alignItems: "center", gap: 12 },
    categoryManageButton: { minHeight: 58, borderWidth: 1, borderRadius: 8, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 11 },
    preferenceTitle: { fontSize: 14, fontWeight: "700", letterSpacing: 0 },
    memberHeader: { marginTop: 4, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    memberCount: { fontSize: 12, fontWeight: "700", letterSpacing: 0 },
    memberRow: { minHeight: 62, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", gap: 10 },
    avatar: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center" },
    memberName: { fontSize: 13, fontWeight: "700", letterSpacing: 0 },
    memberActions: { flexDirection: "row", alignItems: "center", gap: 2 },
    roleButton: { height: 32, minWidth: 48, borderWidth: 1, borderRadius: 7, alignItems: "center", justifyContent: "center", paddingHorizontal: 8 },
    roleButtonText: { fontSize: 11, fontWeight: "800", letterSpacing: 0 },
    smallIcon: { width: 34, height: 34, alignItems: "center", justifyContent: "center" },
    roleStatic: { fontSize: 11, fontWeight: "700", letterSpacing: 0 },
    dangerButton: { marginTop: 8, height: 44, borderWidth: 1, borderRadius: 8, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
    dangerText: { fontSize: 13, fontWeight: "800", letterSpacing: 0 },
    disabledAction: { opacity: 0.45 },
});

export default styles;
