import { StyleSheet } from 'react-native';

import type { AppColors } from '../../src/modules/theme/ThemeContext';

const BRAND_BLUE = '#246BFE';

/** 캘린더 가져오기 화면의 정적 스타일 묶음을 생성합니다. */
export function createCalendarImportStylesPart3(
  colors: AppColors,
  isDark: boolean,
  brandTint: string,
) {
  return StyleSheet.create({
    categoryAssignmentDisclosureDescription: {
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '800',
    },
    categoryAssignmentDisclosureCount: {
      color: BRAND_BLUE,
      fontSize: 10,
      fontWeight: '900',
    },
    categoryAssignmentList: {
      overflow: 'hidden',
      borderRadius: 12,
      backgroundColor: colors.surface2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    categoryAssignmentItem: {
      backgroundColor: colors.surface2,
    },
    categoryAssignmentItemDivider: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    categoryAssignmentRow: {
      minHeight: 58,
      paddingHorizontal: 12,
      paddingVertical: 9,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
    },
    categoryAssignmentSourceIcon: {
      width: 8,
      height: 30,
      borderRadius: 4,
    },
    categoryAssignmentSourceCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    categoryAssignmentSourceTitle: {
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '900',
    },
    categoryAssignmentSourceCount: {
      color: colors.textSecondary,
      fontSize: 10,
      lineHeight: 14,
      fontWeight: '800',
    },
    categoryAssignmentSourceCountCustom: {
      color: BRAND_BLUE,
    },
    categoryAssignmentValue: {
      maxWidth: '48%',
      minHeight: 30,
      paddingLeft: 9,
      paddingRight: 7,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 10,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.04)',
    },
    categoryAssignmentValueDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
    },
    categoryAssignmentValueText: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 11,
      fontWeight: '900',
    },
    categoryAssignmentOptions: {
      paddingHorizontal: 12,
      paddingBottom: 12,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
    },
    categoryStatus: {
      minHeight: 52,
      borderRadius: 15,
      paddingHorizontal: 13,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      backgroundColor: colors.surface2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    categoryStatusError: {
      alignItems: 'flex-start',
    },
    categoryStatusCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    categoryStatusTitle: {
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '900',
    },
    categoryStatusText: {
      flexShrink: 1,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '800',
    },
    categoryGroupList: {
      gap: 14,
    },
    categoryGroup: {
      gap: 8,
    },
    categoryGroupHeader: {
      minHeight: 20,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    categoryGroupTitle: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: '900',
    },
    categoryGroupScope: {
      color: colors.textSecondary,
      fontSize: 10,
      fontWeight: '800',
    },
    defaultOriginWrap: {
      gap: 10,
    },
    originSearchRow: {
      minHeight: 54,
      borderRadius: 14,
      paddingLeft: 14,
      paddingRight: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    originSearchRowSelected: {
      borderColor: BRAND_BLUE,
    },
    originSearchInput: {
      flex: 1,
      minWidth: 0,
      height: 52,
      paddingVertical: 0,
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '800',
    },
    originSearchButton: {
      width: 38,
      height: 38,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: BRAND_BLUE,
    },
    selectedOriginRow: {
      minHeight: 48,
      paddingHorizontal: 12,
      paddingVertical: 9,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      borderRadius: 14,
      backgroundColor: brandTint,
    },
    selectedOriginCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    selectedOriginTitle: {
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '900',
    },
    selectedOriginAddress: {
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '700',
    },
    originResultList: {
      overflow: 'hidden',
      borderRadius: 16,
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    originResultRow: {
      minHeight: 58,
      paddingHorizontal: 13,
      paddingVertical: 9,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    originResultRowDivider: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    originResultCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    originResultTitle: {
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '900',
    },
    originResultAddress: {
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '700',
    },
    originSearchError: {
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '800',
    },
    routePreparationNotice: {
      minHeight: 52,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      borderRadius: 15,
      backgroundColor: isDark ? 'rgba(255,255,255,0.055)' : 'rgba(0,0,0,0.035)',
    },
    routePreparationNoticeText: {
      flex: 1,
      minWidth: 0,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '800',
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    optionChip: {
      minHeight: 42,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface2,
      paddingHorizontal: 13,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
    },
    optionChipActive: {
      backgroundColor: BRAND_BLUE,
      borderColor: BRAND_BLUE,
    },
    optionChipText: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '900',
    },
    optionChipTextActive: {
      color: '#FFFFFF',
    },
    optionColorDot: {
      width: 9,
      height: 9,
      borderRadius: 5,
    },
    switchRow: {
      marginTop: 10,
      minHeight: 70,
      borderRadius: 14,
      paddingHorizontal: 15,
      paddingVertical: 13,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      backgroundColor: colors.surface2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    switchTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    switchControl: {
      transform: [{ scale: 0.88 }],
    },
    switchControlWrap: {
      width: 52,
      height: 42,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
    },
    switchTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '900',
    },
    switchHint: {
      marginTop: 4,
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '800',
    },
    footer: {
      marginHorizontal: -22,
      paddingTop: 12,
      paddingHorizontal: 22,
      gap: 4,
      backgroundColor: isDark ? '#0F1115' : '#F8F9FB',
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    footerNotice: {
      minHeight: 28,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingBottom: 4,
    },
    footerNoticeText: {
      flexShrink: 1,
      color: colors.textSecondary,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '800',
    },
    importLoadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 50,
      elevation: 50,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 28,
      backgroundColor: isDark ? 'rgba(8,10,14,0.78)' : 'rgba(248,249,251,0.82)',
    },
    importLoadingCard: {
      width: '100%',
      maxWidth: 320,
      minHeight: 168,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
      paddingVertical: 24,
      borderRadius: 22,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surface2,
    },
    importLoadingTitle: {
      marginTop: 18,
      color: colors.textPrimary,
      fontSize: 17,
      fontWeight: '900',
    },
    importLoadingText: {
      marginTop: 7,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '800',
      textAlign: 'center',
    },
    ghostButton: {
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    primaryButton: {
      minHeight: 56,
      borderRadius: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: BRAND_BLUE,
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '900',
    },
    primaryButtonDisabled: {
      backgroundColor: isDark ? '#272A31' : '#E4E7EC',
    },
    primaryButtonTextDisabled: {
      color: colors.textDisabled,
    },
    ghostButtonText: {
      color: colors.textSecondary,
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 22,
      fontWeight: '900',
      paddingVertical: 4,
    },
    disabled: {
      opacity: 0.55,
    },
    disabledText: {
      opacity: 0.55,
    },
    pressed: {
      opacity: 0.72,
      transform: [{ scale: 0.99 }],
    },
  });
}
