import { StyleSheet } from "react-native";

import type { RoutePlannerStyleOptions } from "../styles";

/** 경로 계획 화면의 mapSearch 영역 정적 스타일을 생성합니다. */
export function createMapSearchStyles(options: RoutePlannerStyleOptions) {
    const {
        TRANSIT_DETAIL_ACTION_BAR_MIN_HEIGHT,
        TRANSIT_DETAIL_ACTION_BAR_TOP_PADDING,
        TRANSIT_DETAIL_ACTION_BUTTON_HEIGHT,
        ORIGIN_COLOR,
        DESTINATION_COLOR,
    } = options;
    return {
        container: {
        flex: 1,
    },
        routeDetailScreen: {
        flex: 1,
        backgroundColor: "#0B0C0F",
    },
        routeDetailMapHeader: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        paddingHorizontal: 14,
        paddingBottom: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        zIndex: 6,
    },
        routeDetailFloatingButton: {
        width: 48,
        height: 48,
        borderRadius: 24,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(7,9,13,0.86)",
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: "rgba(255,255,255,0.10)",
    },
        routeDetailTitlePill: {
        flex: 1,
        minHeight: 48,
        minWidth: 0,
        borderRadius: 24,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
        gap: 8,
        backgroundColor: "rgba(7,9,13,0.86)",
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: "rgba(255,255,255,0.10)",
    },
        routeDetailHeaderTitle: {
        flex: 1,
        minWidth: 0,
        color: "#F5F7FA",
        fontSize: 16,
        fontWeight: "900",
        lineHeight: 22,
    },
        routeDetailMapFrame: {
        position: "relative",
        overflow: "hidden",
        backgroundColor: "#111827",
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderColor: "rgba(255,255,255,0.08)",
    },
        routeDetailMapView: {
        ...StyleSheet.absoluteFillObject,
    },
        routeDetailPanel: {
        flex: 1,
        marginTop: -22,
        borderTopLeftRadius: 22,
        borderTopRightRadius: 22,
        backgroundColor: "#1C1D22",
        overflow: "hidden",
        zIndex: 5,
    },
        routeDetailSheetHandle: {
        alignSelf: "center",
        width: 54,
        height: 5,
        borderRadius: 999,
        marginTop: 10,
        marginBottom: 6,
        backgroundColor: "rgba(156,163,175,0.54)",
    },
        routeDetailPanelScroll: {
        flex: 1,
    },
        routeDetailPanelContent: {
        paddingHorizontal: 0,
        paddingTop: 8,
    },
        routeDetailSummaryCard: {
        borderWidth: 0,
        borderRadius: 0,
        backgroundColor: "transparent",
        paddingHorizontal: 24,
        paddingTop: 6,
        paddingBottom: 9,
        gap: 7,
    },
        routeDetailCompactSummary: {
        gap: 5,
    },
        routeDetailCompactDuration: {
        color: "#FFFFFF",
        fontSize: 38,
        fontWeight: "900",
        lineHeight: 44,
    },
        routeDetailMetaText: {
        color: "#C8CDD6",
        fontSize: 15,
        fontWeight: "800",
        lineHeight: 20,
    },
        routeDetailDivider: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: "rgba(255,255,255,0.10)",
    },
        routeDetailBaseTimeText: {
        color: "#C8CDD6",
        fontSize: 16,
        fontWeight: "900",
        lineHeight: 22,
        paddingTop: 0,
    },
        routeDetailEmptyText: {
        color: "#9CA3AF",
        fontSize: 13,
        fontWeight: "700",
        lineHeight: 18,
    },
        routeDetailLoadingRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
        routeDetailActionBar: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 9,
        elevation: 9,
        minHeight: TRANSIT_DETAIL_ACTION_BAR_MIN_HEIGHT,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: "rgba(255,255,255,0.10)",
        paddingTop: TRANSIT_DETAIL_ACTION_BAR_TOP_PADDING,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "flex-end",
        gap: 12,
        backgroundColor: "rgba(9,10,13,0.97)",
    },
        routeDetailActionEta: {
        flex: 1,
        paddingBottom: 2,
        minWidth: 82,
    },
        routeDetailActionDuration: {
        color: "#FFFFFF",
        fontSize: 22,
        fontWeight: "900",
        lineHeight: 27,
    },
        routeDetailActionArrival: {
        color: "#F5F7FA",
        fontSize: 15,
        fontWeight: "800",
        lineHeight: 20,
    },
        routeDetailActionButtons: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        flexShrink: 0,
    },
        routeDetailPreviewButton: {
        height: TRANSIT_DETAIL_ACTION_BUTTON_HEIGHT,
        minWidth: 108,
        borderRadius: 999,
        paddingHorizontal: 16,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 7,
        borderWidth: 1.4,
        borderColor: "rgba(75,157,255,0.42)",
        backgroundColor: "rgba(12,16,22,0.96)",
    },
        routeDetailPreviewButtonText: {
        color: "#4B9DFF",
        fontSize: 16,
        fontWeight: "900",
        lineHeight: 20,
    },
        routeDetailSaveButton: {
        height: TRANSIT_DETAIL_ACTION_BUTTON_HEIGHT,
        minWidth: 116,
        borderRadius: 999,
        paddingHorizontal: 17,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 7,
        backgroundColor: "#4B9DFF",
    },
        routeDetailSaveButtonText: {
        color: "#111317",
        fontSize: 16,
        fontWeight: "900",
        lineHeight: 20,
    },
        fullMap: {
        ...StyleSheet.absoluteFillObject,
    },
        mapLoadingSurface: {
        ...StyleSheet.absoluteFillObject,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 6,
    },
        mapLoadingSurfaceLight: {
        backgroundColor: "#EEF2F6",
    },
        mapLoadingSurfaceDark: {
        backgroundColor: "#0B1220",
    },
        transitMapRouteHeader: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 30,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        paddingHorizontal: 10,
        paddingBottom: 2,
    },
        transitMapHeaderIconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000000",
        shadowOpacity: 0.16,
        shadowRadius: 7,
        shadowOffset: { width: 0, height: 3 },
    },
        transitMapRouteSummaryPill: {
        flex: 1,
        minWidth: 0,
        height: 40,
        borderRadius: 20,
        paddingHorizontal: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 5,
        backgroundColor: "#5AA0FF",
        shadowColor: "#000000",
        shadowOpacity: 0.16,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
    },
        transitMapRouteSummaryText: {
        flexShrink: 1,
        minWidth: 0,
        color: "#111317",
        fontSize: 12.5,
        fontWeight: "900",
        lineHeight: 19,
        letterSpacing: 0,
    },
        transitMapRouteNextChip: {
        height: 40,
        width: 82,
        borderRadius: 20,
        paddingHorizontal: 8,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
        backgroundColor: "rgba(10,11,14,0.92)",
        shadowColor: "#000000",
        shadowOpacity: 0.18,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
    },
        transitMapRouteNextText: {
        flexShrink: 1,
        minWidth: 0,
        fontSize: 11.5,
        fontWeight: "900",
        lineHeight: 19,
        letterSpacing: 0,
    },
        transitMapScheduleButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000000",
        shadowOpacity: 0.16,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
    },
        topOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        paddingHorizontal: 12,
        gap: 7,
    },
        searchOverlayRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
        inlineCloseBtn: {
        width: 54,
        height: 54,
        borderRadius: 999,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: "center",
        justifyContent: "center",
    },
        inlineCloseBtnText: {
        fontSize: 46,
        fontWeight: "300",
        lineHeight: 52,
        marginTop: -4,
    },
        searchField: {
        flex: 1,
    },
        searchInputWrap: {
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        borderRadius: 12,
        paddingHorizontal: 11,
    },
        searchInput: {
        flex: 1,
        paddingVertical: 8,
        fontSize: 15,
        fontWeight: "600",
    },
        searchIcon: {
        paddingLeft: 8,
        justifyContent: "center",
        alignItems: "center",
    },
        targetCompactWrap: {
        width: 84,
        minHeight: 38,
        borderWidth: 1,
        borderRadius: 12,
        flexDirection: "row",
        padding: 3,
        gap: 3,
    },
        plannerScheduleButton: {
        width: 44,
        minHeight: 44,
        borderWidth: 1,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
    },
        targetCompactBtn: {
        flex: 1,
        borderRadius: 9,
        alignItems: "center",
        justifyContent: "center",
    },
        targetCompactBtnActiveOrigin: {
        backgroundColor: ORIGIN_COLOR,
    },
        targetCompactBtnActiveDestination: {
        backgroundColor: DESTINATION_COLOR,
    },
        targetCompactText: {
        fontSize: 12,
        fontWeight: "800",
    },
        targetCompactTextActive: {
        color: "#FFFFFF",
    },
        searchResultWrap: {
        maxHeight: 220,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 10,
        overflow: "hidden",
    },
        searchResultItem: {
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
        searchStateRow: {
        paddingHorizontal: 14,
        paddingVertical: 12,
        gap: 10,
    },
        searchStateText: {
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "700",
    },
        searchStateRetryButton: {
        alignSelf: "flex-start",
        minHeight: 36,
        borderRadius: 9,
        paddingHorizontal: 13,
        alignItems: "center",
        justifyContent: "center",
    },
        searchStateRetryText: {
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "800",
    },
        routePreviewCard: {
        borderWidth: 1,
        borderRadius: 14,
        paddingHorizontal: 11,
        paddingVertical: 9,
        gap: 4,
    },
        overlaySurface: {
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 3 },
        elevation: 3,
    },
        routePreviewMain: {
        fontSize: 14,
        fontWeight: "800",
        lineHeight: 18,
    },
        routePreviewSub: {
        fontSize: 12,
        fontWeight: "600",
        lineHeight: 15,
    },
        routePreviewActionRow: {
        marginTop: 2,
        flexDirection: "row",
        justifyContent: "flex-end",
    },
        routePreviewActionBtn: {
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 7,
    },
        routePreviewActionText: {
        fontSize: 11,
        fontWeight: "800",
    },
        transitLegendInlineRow: {
        flexDirection: "row",
        alignItems: "center",
        flexWrap: "wrap",
        gap: 6,
    },
        transitLegendInlineChip: {
        borderWidth: 1,
        borderRadius: 999,
        paddingHorizontal: 8,
        paddingVertical: 4,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
        transitLegendHintText: {
        fontSize: 11,
        fontWeight: "600",
        lineHeight: 14,
    },
        transitLegendSwatch: {
        width: 14,
        height: 6,
        borderRadius: 99,
    },
        transitLegendText: {
        fontSize: 11,
        fontWeight: "800",
    },
    } as const;
}
