import { StyleSheet } from "react-native";

import type { RoutePlannerStyleOptions } from "../styles";

/** 경로 계획 화면의 reference 영역 정적 스타일을 생성합니다. */
export function createReferenceStyles(options: RoutePlannerStyleOptions) {
    const {
        ORIGIN_COLOR,
        DESTINATION_COLOR,
    } = options;
    return {
        transitReferenceScreen: {
        flex: 1,
        backgroundColor: "#1C1C1E",
    },
        transitReferenceScrollContent: {
        backgroundColor: "#1C1C1E",
    },
        transitReferenceAddressCard: {
        marginHorizontal: 16,
        borderWidth: 1,
        borderColor: "#303033",
        borderRadius: 18,
        overflow: "hidden",
        backgroundColor: "#1D1D1F",
    },
        transitReferenceRouteRows: {
        minHeight: 74,
        flexDirection: "row",
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 6,
    },
        transitReferenceSwapRail: {
        width: 36,
        alignItems: "flex-start",
        justifyContent: "center",
    },
        transitReferenceSwapText: {
        color: "#A9A9AC",
        fontSize: 24,
        fontWeight: "700",
    },
        transitReferenceAddressContent: {
        flex: 1,
    },
        transitReferenceAddressRow: {
        minHeight: 31,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
        transitReferencePointDot: {
        width: 12,
        height: 12,
        borderRadius: 999,
        borderWidth: 3,
    },
        transitReferenceOriginDot: {
        borderColor: "rgba(34,197,94,0.36)",
        backgroundColor: ORIGIN_COLOR,
    },
        transitReferenceDestinationDot: {
        borderColor: "rgba(255,68,68,0.35)",
        backgroundColor: DESTINATION_COLOR,
    },
        transitReferenceAddressText: {
        flex: 1,
        color: "#E5E5EA",
        fontSize: 16,
        fontWeight: "900",
        letterSpacing: -0.2,
        lineHeight: 22,
    },
        transitReferenceCloseButton: {
        width: 28,
        height: 28,
        alignItems: "center",
        justifyContent: "center",
    },
        transitReferenceCloseText: {
        color: "#A5A5AA",
        fontSize: 30,
        fontWeight: "300",
        lineHeight: 30,
    },
        transitReferenceMoreText: {
        width: 28,
        color: "#8E8E93",
        fontSize: 24,
        lineHeight: 27,
        textAlign: "center",
    },
        transitReferenceAddressDivider: {
        height: StyleSheet.hairlineWidth,
        marginLeft: 30,
        backgroundColor: "#343438",
    },
        transitReferenceEntranceRow: {
        minHeight: 36,
        paddingHorizontal: 18,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: "#2C2C2E",
    },
        transitReferenceEntranceLabel: {
        color: "#A7A7AA",
        fontSize: 14,
        fontWeight: "900",
    },
        transitReferenceEntranceAction: {
        color: "#4D9BFF",
        fontSize: 14,
        fontWeight: "900",
    },
        transitReferenceModeRow: {
        height: 56,
        marginTop: 8,
        paddingHorizontal: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: "#2D2D30",
    },
        transitReferenceModeButton: {
        minWidth: 72,
        minHeight: 38,
        borderRadius: 999,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
    },
        transitReferenceModeButtonSelected: {
        minWidth: 132,
        backgroundColor: "#5AA0FF",
    },
        transitReferenceModeText: {
        color: "#C7C7CC",
        fontSize: 15,
        fontWeight: "900",
    },
        transitReferenceModeTextSelected: {
        color: "#0B0B0C",
        fontSize: 17,
    },
        transitReferenceFilterRow: {
        height: 56,
        flexDirection: "row",
        alignItems: "flex-end",
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: "#303033",
        paddingHorizontal: 16,
        gap: 24,
    },
        transitReferenceFilterTab: {
        minHeight: 54,
        justifyContent: "flex-end",
        paddingBottom: 11,
    },
        transitReferenceFilterText: {
        color: "#8F8F94",
        fontSize: 16,
        fontWeight: "900",
        lineHeight: 22,
    },
        transitReferenceFilterTextSelected: {
        color: "#E5E5EA",
    },
        transitReferenceFilterUnderline: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        height: 3,
        backgroundColor: "#E5E5EA",
    },
        transitReferenceControlRow: {
        height: 58,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: "#303033",
    },
        transitReferenceDepartureText: {
        color: "#D7D7DA",
        fontSize: 15,
        fontWeight: "900",
    },
        transitReferenceDepartureBlue: {
        color: "#4D9BFF",
    },
        transitReferenceSortText: {
        color: "#D2D2D5",
        fontSize: 15,
        fontWeight: "800",
    },
        transitReferenceDetailPanel: {
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: 24,
        backgroundColor: "#1F1F1F",
    },
        transitReferenceLoadingRow: {
        minHeight: 120,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
    },
        transitReferenceLoadingText: {
        color: "#B8B8B8",
        fontSize: 14,
        fontWeight: "800",
    },
        transitReferenceStateText: {
        color: "#B8B8B8",
        paddingVertical: 28,
        fontSize: 14,
        fontWeight: "800",
        textAlign: "center",
    },
        transitReferenceSummaryHeader: {
        marginTop: 16,
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 12,
    },
        transitReferenceSummaryMain: {
        flex: 1,
    },
        transitReferenceOptimalText: {
        color: "#4D9BFF",
        fontSize: 14,
        fontWeight: "900",
        lineHeight: 18,
        marginBottom: 4,
    },
        transitReferenceDurationText: {
        color: "#F2F2F7",
        fontSize: 36,
        fontWeight: "900",
        letterSpacing: -1.4,
        lineHeight: 41,
    },
        transitReferenceRouteMetaText: {
        color: "#C7C7CC",
        fontSize: 15,
        fontWeight: "800",
        lineHeight: 21,
        marginTop: 3,
    },
        transitReferenceFeedbackButton: {
        marginTop: 7,
        borderWidth: 1,
        borderColor: "#4A4A4D",
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
        transitReferenceFeedbackText: {
        color: "#D3D3D6",
        fontSize: 13,
        fontWeight: "900",
    },
        transitReferenceRouteSummaryText: {
        color: "#F2F2F7",
        fontSize: 16,
        fontWeight: "900",
        lineHeight: 22,
        marginTop: 8,
    },
        transitReferenceProgressTrack: {
        height: 21,
        marginTop: 8,
        flexDirection: "row",
        alignItems: "center",
        borderRadius: 999,
        overflow: "hidden",
    },
        transitReferenceProgressSegment: {
        height: "100%",
        minWidth: 28,
        borderRadius: 999,
        alignItems: "center",
        justifyContent: "center",
    },
        transitReferenceProgressText: {
        color: "#FFFFFF",
        fontSize: 12,
        fontWeight: "900",
    },
        transitReferenceFullTimeline: {
        marginTop: 16,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: "#323235",
        paddingTop: 12,
    },
        transitReferenceTimelineItem: {
        flexDirection: "row",
        minHeight: 62,
        borderRadius: 12,
    },
        transitReferenceTimelineItemFocused: {
        backgroundColor: "rgba(77,155,255,0.14)",
    },
        transitReferenceTimelineRail: {
        width: 40,
        alignItems: "center",
    },
        transitReferenceTimelineDot: {
        width: 24,
        height: 24,
        borderRadius: 999,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 2,
    },
        transitReferenceTimelineDotText: {
        color: "#FFFFFF",
        fontSize: 13,
        fontWeight: "900",
    },
        transitReferenceTimelineLine: {
        width: 2,
        flex: 1,
        marginTop: 5,
        marginBottom: 5,
        backgroundColor: "#38383B",
    },
        transitReferenceTimelineContent: {
        flex: 1,
        paddingBottom: 13,
        gap: 4,
    },
        transitReferenceTimelineTopRow: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 10,
    },
        transitReferenceTimelineTitle: {
        flex: 1,
        color: "#F2F2F7",
        fontSize: 17,
        fontWeight: "900",
        lineHeight: 23,
        letterSpacing: -0.5,
    },
        transitReferenceTimelineMeta: {
        flexShrink: 0,
        color: "#B8B8B8",
        fontSize: 14,
        fontWeight: "900",
        lineHeight: 20,
    },
        transitReferenceTimelineAssist: {
        color: "#B8B8B8",
        fontSize: 14,
        fontWeight: "800",
        lineHeight: 20,
    },
        transitReferenceSaveButton: {
        minHeight: 56,
        marginTop: 10,
        borderWidth: 1,
        borderColor: "#55555A",
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
        transitReferenceSaveText: {
        color: "#4D9BFF",
        fontSize: 17,
        fontWeight: "900",
    },
    } as const;
}
