import { StyleSheet } from "react-native";

/** RouteStepTimeline 화면의 정적 시각 규칙입니다. 화면 로직과 독립적으로 조정할 수 있도록 분리했습니다. */
const styles = StyleSheet.create({
    root: {
        gap: 0,
    },
    item: {
        flexDirection: "row",
        borderWidth: 0,
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 0,
    },
    itemCompact: {
        paddingVertical: 1,
    },
    itemCompactFocused: {
        backgroundColor: "transparent",
        borderColor: "transparent",
    },
    itemPressTarget: {
        flex: 1,
        minWidth: 0,
        flexDirection: "row",
    },
    disclosureButton: {
        position: "absolute",
        right: -4,
        width: 24,
        height: 24,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 3,
    },
    disclosureButtonRegular: {
        top: 10,
    },
    disclosureButtonCompact: {
        top: 3,
    },
    rail: {
        width: 42,
        alignItems: "center",
    },
    railCompact: {
        width: 56,
    },
    dot: {
        width: 32,
        height: 32,
        borderRadius: 999,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 2,
    },
    dotCompact: {
        width: 32,
        height: 32,
        borderRadius: 999,
        borderWidth: 1.5,
    },
    originGlyphOuter: {
        width: 17,
        height: 17,
        borderRadius: 999,
        borderWidth: 4,
        alignItems: "center",
        justifyContent: "center",
    },
    originGlyphOuterCompact: {
        width: 18,
        height: 18,
        borderWidth: 4,
    },
    originGlyphCore: {
        width: 4,
        height: 4,
        borderRadius: 999,
    },
    originGlyphCoreCompact: {
        width: 4,
        height: 4,
    },
    line: {
        width: 4,
        flex: 1,
        minHeight: 30,
        marginTop: 2,
        borderRadius: 2,
        opacity: 0.92,
    },
    lineCompact: {
        width: 5,
        minHeight: 46,
        marginTop: 0,
    },
    timelineClockBadge: {
        position: "absolute",
        top: 35,
        minWidth: 48,
        height: 23,
        borderRadius: 5,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 5,
        zIndex: 3,
    },
    timelineClockText: {
        fontSize: 12,
        fontWeight: "800",
        lineHeight: 16,
        letterSpacing: 0,
    },
    body: {
        flex: 1,
        minWidth: 0,
        paddingTop: 0,
        paddingBottom: 10,
    },
    bodyCompact: {
        paddingTop: 2,
        paddingBottom: 6,
    },
    titleRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    titleRowCompact: {
        gap: 8,
    },
    titleRowWithDisclosure: {
        paddingRight: 28,
    },
    badge: {
        minWidth: 32,
        maxWidth: 74,
        height: 22,
        borderRadius: 6,
        paddingHorizontal: 7,
        alignItems: "center",
        justifyContent: "center",
    },
    badgeCompact: {
        height: 25,
        borderRadius: 7,
        paddingHorizontal: 9,
    },
    pointBadge: {
        minWidth: 36,
        height: 22,
        borderRadius: 6,
        paddingHorizontal: 6,
        alignItems: "center",
        justifyContent: "center",
    },
    pointBadgeCompact: {
        minWidth: 42,
        height: 25,
        borderRadius: 7,
    },
    pointBadgeText: {
        color: "#FFFFFF",
        fontSize: 10,
        fontWeight: "900",
        letterSpacing: 0,
    },
    pointBadgeTextCompact: {
        fontSize: 12,
        lineHeight: 15,
    },
    badgeText: {
        color: "#FFFFFF",
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 0,
    },
    badgeTextCompact: {
        fontSize: 13,
        lineHeight: 16,
    },
    title: {
        flex: 1,
        minWidth: 0,
        fontSize: 17,
        fontWeight: "900",
        lineHeight: 23,
        letterSpacing: 0,
    },
    titleCompact: {
        fontSize: 17,
        fontWeight: "900",
        lineHeight: 23,
    },
    titleSuffix: {
        fontSize: 15,
        fontWeight: "900",
        lineHeight: 22,
    },
    description: {
        marginTop: 6,
        fontSize: 14,
        fontWeight: "800",
        lineHeight: 20,
    },
    descriptionCompact: {
        marginTop: 4,
        fontSize: 15,
        fontWeight: "800",
        lineHeight: 20,
    },
    rideInfoRow: {
        marginTop: 4,
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 10,
    },
    rideInfoTextStack: {
        flex: 1,
        minWidth: 0,
    },
    rideAssistText: {
        marginTop: 3,
        fontSize: 14,
        fontWeight: "800",
        lineHeight: 19,
        letterSpacing: 0,
    },
    boardingGuideRow: {
        marginTop: 8,
        marginRight: 4,
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 6,
    },
    boardingGuideChip: {
        maxWidth: "100%",
        minHeight: 28,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 7,
        paddingHorizontal: 8,
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
    },
    boardingGuideText: {
        flexShrink: 1,
        fontSize: 12,
        fontWeight: "800",
        lineHeight: 16,
    },
    rideActionRow: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        gap: 6,
        paddingTop: 1,
    },
    rideActionStack: {
        alignItems: "flex-end",
        gap: 3,
    },
    rideActionChip: {
        minHeight: 28,
        borderRadius: 999,
        borderWidth: StyleSheet.hairlineWidth,
        paddingHorizontal: 10,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(255,255,255,0.03)",
    },
    rideActionText: {
        fontSize: 13,
        fontWeight: "900",
        lineHeight: 17,
        letterSpacing: 0,
    },
    arrivalFreshnessText: {
        fontSize: 11,
        fontWeight: "800",
        lineHeight: 14,
        letterSpacing: 0,
    },
    arrivalCard: {
        marginTop: 10,
        marginRight: 4,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 14,
        backgroundColor: "rgba(255,255,255,0.025)",
        gap: 9,
    },
    trainArrivalRow: {
        minHeight: 24,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    busArrivalRow: {
        minHeight: 30,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    arrivalInlineRow: {
        minHeight: 24,
        marginTop: 7,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    arrivalInlineText: {
        flex: 1,
        minWidth: 0,
        fontSize: 13,
        fontWeight: "700",
        lineHeight: 18,
        letterSpacing: 0,
    },
    arrivalClockText: {
        minWidth: 52,
        fontSize: 17,
        fontWeight: "900",
        lineHeight: 22,
        letterSpacing: 0,
    },
    arrivalWaitText: {
        color: "#FF5A52",
        fontSize: 16,
        fontWeight: "900",
        lineHeight: 21,
        letterSpacing: 0,
    },
    arrivalMutedText: {
        flex: 1,
        minWidth: 0,
        fontSize: 15,
        fontWeight: "800",
        lineHeight: 20,
        letterSpacing: 0,
    },
    arrivalAttributeList: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
    },
    arrivalAttributeBadge: {
        minWidth: 32,
        height: 22,
        borderRadius: 999,
        borderWidth: 1.2,
        paddingHorizontal: 6,
        alignItems: "center",
        justifyContent: "center",
    },
    arrivalAttributeText: {
        fontSize: 12,
        fontWeight: "900",
        lineHeight: 15,
    },
    busArrivalBadge: {
        minWidth: 44,
        maxWidth: 70,
        height: 28,
        borderRadius: 7,
        paddingHorizontal: 8,
        alignItems: "center",
        justifyContent: "center",
    },
    busArrivalBadgeText: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "900",
        lineHeight: 18,
    },
    itemDivider: {
        height: StyleSheet.hairlineWidth,
        marginTop: 12,
        marginRight: -2,
    },
    stopList: {
        marginTop: 14,
        marginRight: 4,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 12,
        gap: 0,
    },
    stopRow: {
        minHeight: 30,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        borderRadius: 6,
        paddingHorizontal: 4,
    },
    stopRail: {
        width: 12,
        alignSelf: "stretch",
        alignItems: "center",
    },
    stopDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        borderWidth: 1.5,
        marginTop: 9,
        zIndex: 2,
    },
    stopLine: {
        width: 2,
        flex: 1,
        opacity: 0.48,
    },
    stopText: {
        flex: 1,
        minWidth: 0,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: 0,
    },
});

export default styles;
