import { StyleSheet } from "react-native";

/** 경로 선택 화면의 base 영역 정적 스타일입니다. */
const baseStyles = {
    screen: {
        flex: 1,
    },
    headerRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        paddingHorizontal: 16,
        paddingBottom: 12,
    },
    headerButton: {
        width: 42,
        height: 42,
        borderRadius: 14,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: "center",
        justifyContent: "center",
    },
    headerButtonText: {
        marginTop: -3,
        fontSize: 38,
        fontWeight: "300",
        lineHeight: 42,
    },
    headerTitleWrap: {
        flex: 1,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "900",
        lineHeight: 25,
    },
    headerSubtitle: {
        marginTop: 1,
        fontSize: 12,
        fontWeight: "600",
    },
    headerScheduleButton: {
        minWidth: 64,
        height: 42,
        borderRadius: 14,
        borderWidth: StyleSheet.hairlineWidth,
        paddingHorizontal: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 5,
    },
    headerScheduleButtonText: {
        fontSize: 13,
        fontWeight: "900",
        lineHeight: 16,
        letterSpacing: 0,
    },
    content: {
        paddingHorizontal: 16,
        gap: 10,
    },
    routeResultHeaderRow: {
        flexDirection: "row",
        alignItems: "stretch",
        gap: 8,
    },
    routeCard: {
        borderWidth: 1,
        borderRadius: 14,
        padding: 14,
        gap: 14,
    },
    routeCompactCardInHeader: {
        flex: 1,
    },
    routeResultScheduleButton: {
        width: 62,
        borderRadius: 20,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
    },
    routeResultScheduleButtonText: {
        fontSize: 11,
        fontWeight: "900",
        lineHeight: 14,
        letterSpacing: 0,
    },
    routeInputRows: {
        flexDirection: "row",
        alignItems: "center",
    },
    routeRail: {
        width: 24,
        alignItems: "center",
        paddingVertical: 8,
    },
    routeDot: {
        width: 12,
        height: 12,
        borderRadius: 999,
        borderWidth: 3.5,
    },
    routeRailLine: {
        width: 2,
        flex: 1,
        minHeight: 42,
        marginVertical: 4,
    },
    routeInputs: {
        flex: 1,
    },
    routeInput: {
        minHeight: 40,
        borderBottomWidth: StyleSheet.hairlineWidth,
        fontSize: 14,
        fontWeight: "800",
    },
    swapButton: {
        width: 34,
        height: 60,
        borderRadius: 10,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
        marginLeft: 10,
    },
    swapButtonText: {
        fontSize: 22,
        fontWeight: "800",
        lineHeight: 24,
    },
    searchModeHeader: {
        minHeight: 58,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 16,
        paddingBottom: 8,
    },
    searchModeBackButton: {
        width: 34,
        height: 42,
        alignItems: "center",
        justifyContent: "center",
    },
    searchModeBackText: {
        marginTop: -3,
        fontSize: 42,
        fontWeight: "300",
        lineHeight: 44,
    },
    scheduleListIconButton: {
        width: 40,
        height: 40,
        borderRadius: 14,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: "center",
        justifyContent: "center",
    },
    searchModeSearchBox: {
        flex: 1,
        minWidth: 0,
        height: 40,
        borderRadius: 14,
        borderWidth: StyleSheet.hairlineWidth,
        paddingLeft: 13,
        paddingRight: 8,
        flexDirection: "row",
        alignItems: "center",
    },
    searchModeInput: {
        flex: 1,
        minWidth: 0,
        height: 40,
        paddingVertical: 0,
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    searchModeTargetContext: {
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
        marginRight: 8,
    },
    searchModeTargetDot: {
        width: 8,
        height: 8,
        borderRadius: 999,
        borderWidth: 2,
    },
    searchModeTargetText: {
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 0,
    },
    searchModeClearButton: {
        width: 24,
        height: 24,
        borderRadius: 999,
        alignItems: "center",
        justifyContent: "center",
    },
    searchModeClearText: {
        marginTop: -2,
        fontSize: 20,
        fontWeight: "900",
        lineHeight: 22,
    },
    defaultOriginBar: {
        minHeight: 52,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderBottomWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        paddingHorizontal: 20,
        paddingVertical: 8,
    },
    defaultOriginCopy: {
        flex: 1,
        minWidth: 0,
        gap: 2,
    },
    defaultOriginLabel: {
        fontSize: 11,
        fontWeight: "700",
        letterSpacing: 0,
    },
    defaultOriginName: {
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    defaultOriginAction: {
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 0,
    },
    defaultOriginSetupBar: {
        minHeight: 68,
        marginHorizontal: 20,
        marginTop: 2,
        marginBottom: 6,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    defaultOriginSetupIcon: {
        width: 36,
        height: 36,
        borderRadius: 999,
        alignItems: "center",
        justifyContent: "center",
    },
    defaultOriginSetupTitle: {
        fontSize: 13,
        fontWeight: "900",
    },
    defaultOriginSetupDescription: {
        fontSize: 11,
        fontWeight: "600",
        lineHeight: 16,
    },
    searchModeActionRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        paddingHorizontal: 20,
        paddingTop: 4,
        paddingBottom: 10,
    },
    searchModeActionButton: {
        flex: 1,
        minHeight: 58,
        borderRadius: 14,
        borderWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 12,
    },
    searchModeActionText: {
        fontSize: 15,
        fontWeight: "800",
    },
    searchModeContent: {
        flexGrow: 1,
        paddingTop: 4,
    },
    searchModePanel: {
        width: "100%",
    },
} as const;

export default baseStyles;
