import { StyleSheet } from "react-native";

/** 경로 선택 화면의 filters 영역 정적 스타일입니다. */
const filtersStyles = {
    modeRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 10,
        paddingTop: 0,
        paddingBottom: 6,
        paddingHorizontal: 0,
    },
    modeButtonShell: {
        flex: 0,
        minWidth: 50,
    },
    modeButtonShellSelected: {
        flex: 0,
        minWidth: 72,
    },
    modeButton: {
        minHeight: 42,
        borderWidth: 0,
        borderRadius: 18,
        paddingVertical: 7,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 0,
    },
    modeButtonSelected: {
        borderWidth: 1,
        width: 72,
    },
    modeButtonIconOnly: {
        width: 50,
        paddingHorizontal: 0,
    },
    modeButtonText: {
        fontSize: 17,
        fontWeight: "900",
        letterSpacing: 0,
    },
    transitFilterRow: {
        width: "100%",
        justifyContent: "space-between",
        gap: 0,
        paddingHorizontal: 0,
        paddingTop: 0,
        paddingBottom: 0,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: "rgba(255,255,255,0.12)",
    },
    transitFilterTab: {
        position: "relative",
        minHeight: 39,
        borderWidth: 0,
        borderRadius: 0,
        minWidth: 76,
        paddingHorizontal: 2,
        alignItems: "center",
        justifyContent: "center",
    },
    transitFilterIndicator: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        height: 2,
        borderRadius: 999,
    },
    transitFilterText: {
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    routeSortRow: {
        minHeight: 46,
        borderTopWidth: 0,
        borderBottomWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    routeSortPrimaryText: {
        fontSize: 15,
        fontWeight: "900",
        letterSpacing: 0,
    },
    routeSortSecondary: {
        flexDirection: "row",
        alignItems: "center",
        gap: 3,
    },
    routeSortSecondaryText: {
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 0,
    },
    currentRouteNotice: {
        minHeight: 46,
        paddingHorizontal: 8,
        paddingTop: 9,
        paddingBottom: 9,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    currentRouteTimeGroup: {
        flex: 1,
        minWidth: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
    currentRouteNoticeText: {
        fontSize: 13,
        fontWeight: "600",
        lineHeight: 19,
        letterSpacing: 0,
    },
    currentRouteNoticeTimeText: {
        fontSize: 14,
        fontWeight: "800",
        lineHeight: 19,
        letterSpacing: 0,
    },
    currentRouteSortGroup: {
        minHeight: 28,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 2,
    },
    currentRouteSortText: {
        flexShrink: 0,
        fontSize: 13,
        fontWeight: "700",
        lineHeight: 19,
        letterSpacing: 0,
    },
    routeList: {
        gap: 8,
        paddingTop: 2,
    },
    routeCandidateItem: {
        gap: 0,
    },
    emptyCard: {
        minHeight: 84,
        borderWidth: 1,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 18,
        gap: 8,
    },
    emptyText: {
        textAlign: "center",
        fontSize: 13,
        fontWeight: "700",
        lineHeight: 18,
    },
    emptyRetryButton: {
        minHeight: 36,
        borderRadius: 8,
        paddingHorizontal: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
    },
    emptyRetryText: {
        color: "#FFFFFF",
        fontSize: 13,
        fontWeight: "800",
        lineHeight: 17,
        letterSpacing: 0,
    },
} as const;

export default filtersStyles;
