import { StyleSheet } from "react-native";

/** 경로 선택 화면의 routeOptions 영역 정적 스타일입니다. */
const routeOptionsStyles = {
    routeOptionCard: {
        borderRadius: 18,
        borderWidth: 1,
        paddingHorizontal: 0,
        paddingTop: 0,
        paddingBottom: 0,
        gap: 0,
        overflow: "hidden",
    },
    routeOptionCardInactive: {
        borderWidth: 1,
        shadowColor: "#000000",
        shadowOpacity: 0,
        shadowRadius: 0,
        shadowOffset: { width: 0, height: 0 },
        elevation: 0,
    },
    routeOptionCardSelectedLight: {
        borderWidth: 1,
        shadowColor: "#1E68FF",
        shadowOpacity: 0.05,
        shadowRadius: 7,
        shadowOffset: { width: 0, height: 3 },
        elevation: 1,
    },
    routeOptionCardSelectedDark: {
        borderWidth: 1,
        shadowColor: "#2F8CFF",
        shadowOpacity: 0.08,
        shadowRadius: 7,
        shadowOffset: { width: 0, height: 3 },
        elevation: 1,
    },
    routeOptionExpansion: {
        borderTopWidth: StyleSheet.hairlineWidth,
        marginHorizontal: 14,
        paddingTop: 10,
        paddingBottom: 8,
        overflow: "hidden",
    },
    routeDropdownSummaryList: {
        gap: 4,
    },
    routeDropdownSummaryRow: {
        minHeight: 39,
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 10,
        paddingVertical: 3,
    },
    routeDropdownMarkerColumn: {
        width: 26,
        alignItems: "center",
        alignSelf: "stretch",
        paddingTop: 1,
    },
    routeDropdownIcon: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 1.4,
        alignItems: "center",
        justifyContent: "center",
    },
    routeDropdownConnector: {
        width: 2,
        flex: 1,
        minHeight: 11,
        marginTop: 3,
        opacity: 0.32,
        borderRadius: 1,
    },
    routeDropdownStepTextWrap: {
        flex: 1,
        minWidth: 0,
        gap: 1,
        paddingTop: 1,
    },
    routeDropdownStepLine: {
        fontSize: 15,
        fontWeight: "800",
        lineHeight: 20,
        letterSpacing: 0,
    },
    routeDropdownStepMeta: {
        fontSize: 12.5,
        fontWeight: "700",
        lineHeight: 17,
        letterSpacing: 0,
    },
    routeAttributionLink: {
        minHeight: 34,
        borderTopWidth: StyleSheet.hairlineWidth,
        paddingHorizontal: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: 4,
    },
    routeAttributionText: {
        fontSize: 11,
        fontWeight: "600",
        lineHeight: 15,
        letterSpacing: 0,
    },
    routeCardActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 9,
        borderTopWidth: StyleSheet.hairlineWidth,
        paddingTop: 10,
        paddingBottom: 12,
        paddingHorizontal: 14,
    },
    routeCardSecondaryButton: {
        flex: 1,
        minHeight: 42,
        borderWidth: 1,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 5,
        paddingHorizontal: 10,
    },
    routeCardSecondaryButtonText: {
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    routeCardPrimaryButton: {
        flex: 1.15,
        minHeight: 42,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 5,
        paddingHorizontal: 10,
    },
    routeCardPrimaryButtonText: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    routeOptionPressable: {
        paddingHorizontal: 16,
        paddingVertical: 13,
        gap: 7,
    },
    routeOptionHeader: {
        alignItems: "flex-start",
        gap: 8,
    },
    routeOptionHeaderRow: {
        width: "100%",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    routeOptionTitleMetaRow: {
        flex: 1,
        minWidth: 0,
        alignItems: "flex-start",
        gap: 5,
    },
    routeOptionLabelPill: {
        minHeight: 25,
        borderRadius: 999,
        paddingHorizontal: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
    },
    routeOptionTopRow: {
        width: "100%",
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: 12,
    },
    routeOptionLabel: {
        fontSize: 12,
        fontWeight: "900",
        letterSpacing: 0,
        lineHeight: 15,
    },
    routeOptionDuration: {
        flexShrink: 0,
        maxWidth: 164,
        textAlign: "right",
        fontSize: 34,
        fontWeight: "800",
        letterSpacing: 0,
        lineHeight: 39,
    },
    routeOptionDurationWrap: {
        flexShrink: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
    routeOptionTimeFare: {
        flex: 1,
        minWidth: 0,
        fontSize: 15,
        fontWeight: "800",
        lineHeight: 19,
        letterSpacing: 0,
    },
    routeOptionCondition: {
        fontSize: 12,
        fontWeight: "800",
        lineHeight: 17,
        letterSpacing: 0,
    },
    routeMetricRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 5,
        paddingTop: 0,
        paddingBottom: 2,
    },
    routeMetricChip: {
        minHeight: 24,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 999,
        paddingHorizontal: 9,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
    },
    routeMetricText: {
        fontSize: 12,
        fontWeight: "900",
        lineHeight: 14,
        letterSpacing: 0,
    },
    routeStepBadgeRow: {
        gap: 6,
        paddingRight: 2,
    },
    routeStepBadge: {
        minWidth: 38,
        maxWidth: 96,
        minHeight: 24,
        borderWidth: 1,
        borderRadius: 7,
        paddingHorizontal: 8,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
    },
    routeStepBadgeText: {
        fontSize: 10,
        fontWeight: "900",
        letterSpacing: 0,
    },
    routeProgressBlock: {
        width: "100%",
        flexShrink: 1,
        paddingTop: 4,
        paddingBottom: 2,
        overflow: "hidden",
    },
    routeProgressScroll: {
        width: "100%",
        flexGrow: 0,
    },
    routeFlowStrip: {
        width: "100%",
        minHeight: 70,
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "flex-start",
        borderTopWidth: StyleSheet.hairlineWidth,
        paddingTop: 10,
        paddingHorizontal: 0,
        overflow: "hidden",
    },
    routeFlowStripSparseSpacing: {
        justifyContent: "center",
        columnGap: 22,
    },
    routeFlowStripRegularSpacing: {
        justifyContent: "space-between",
        columnGap: 2,
    },
    routeFlowSegment: {
        minWidth: 0,
        alignItems: "center",
        gap: 3,
        paddingHorizontal: 1,
        position: "relative",
    },
    routeFlowSegmentSparse: {
        width: 86,
    },
    routeFlowSegmentRegular: {
        width: 64,
    },
    routeFlowSegmentDense: {
        width: 54,
    },
    routeFlowTopLine: {
        minHeight: 24,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 5,
        maxWidth: "100%",
    },
    routeFlowConnector: {
        position: "absolute",
        top: 30,
        right: -1,
        width: 2,
        height: 18,
        borderRadius: 999,
        opacity: 0.42,
    },
    routeFlowMarker: {
        minHeight: 23,
        maxWidth: "100%",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 4,
    },
    routeFlowLineText: {
        maxWidth: 62,
        fontSize: 13,
        fontWeight: "900",
        letterSpacing: 0,
        lineHeight: 16,
    },
    routeFlowPointText: {
        maxWidth: "100%",
        fontSize: 10.75,
        fontWeight: "800",
        lineHeight: 13.5,
        letterSpacing: 0,
        textAlign: "center",
    },
    routeFlowPathSummary: {
        maxWidth: "100%",
        paddingTop: 2,
        paddingLeft: 2,
        fontSize: 13,
        fontWeight: "700",
        lineHeight: 17,
        letterSpacing: 0,
    },
    routeSelectionActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 9,
        paddingTop: 4,
        paddingBottom: 2,
    },
    routeSelectionSecondaryButton: {
        flex: 1,
        minHeight: 46,
        borderWidth: 1,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 7,
        paddingHorizontal: 10,
    },
    routeSelectionSecondaryButtonText: {
        fontSize: 15,
        fontWeight: "800",
        letterSpacing: 0,
    },
    routeSelectionPrimaryButton: {
        flex: 1.15,
        minHeight: 46,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 10,
    },
    routeSelectionPrimaryButtonText: {
        color: "#FFFFFF",
        fontSize: 15,
        fontWeight: "800",
        letterSpacing: 0,
    },
    routeProgressTrackLight: {
        backgroundColor: "transparent",
    },
    routeProgressTrackDark: {
        backgroundColor: "transparent",
    },
    routeProgressBadgeText: {
        fontSize: 9,
        fontWeight: "900",
        lineHeight: 11,
        letterSpacing: 0,
    },
    routeBoardingSummaryRow: {
        width: "100%",
        minHeight: 32,
        borderTopWidth: StyleSheet.hairlineWidth,
        marginTop: 5,
        paddingTop: 9,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    routeBoardingSummaryText: {
        flex: 1,
        minWidth: 0,
        fontSize: 13,
        fontWeight: "800",
        lineHeight: 17,
        letterSpacing: 0,
    },
    routeOptionDetailTapArea: {
        gap: 12,
    },
    routeOptionFooterRow: {
        flexDirection: "row",
        alignItems: "center",
        alignSelf: "flex-start",
        gap: 4,
        paddingTop: 0,
    },
    routeOptionFooterText: {
        fontSize: 13,
        fontWeight: "900",
    },
    routeOptionFooterIcon: {
        marginTop: -1,
        fontSize: 20,
        fontWeight: "900",
        lineHeight: 20,
    },
} as const;

export default routeOptionsStyles;
