import { StyleSheet } from "react-native";

/** RouteDetailDesignPreview 화면의 정적 시각 규칙입니다. 화면 로직과 독립적으로 조정할 수 있도록 분리했습니다. */
const styles = StyleSheet.create({
    root: { flex: 1, overflow: "hidden" },
    mapRoadEdge: { position: "absolute", justifyContent: "center" },
    mapRoadEdgeMajor: { height: 12, borderRadius: 6 },
    mapRoadEdgeMinor: { height: 7, borderRadius: 4 },
    mapRoad: { marginHorizontal: 1 },
    mapRoadMajor: { height: 9, borderRadius: 5 },
    mapRoadMinor: { height: 5, borderRadius: 3 },
    mapPark: {
        position: "absolute",
        right: -30,
        top: 124,
        width: 180,
        height: 126,
        borderRadius: 48,
        transform: [{ rotate: "-8deg" }],
    },
    mapDistrict: { position: "absolute", fontSize: 10, fontWeight: "600", letterSpacing: 0.3 },
    mapDistrictYongsan: { left: 26, top: 162 },
    mapDistrictSeocho: { right: 28, top: 226 },
    mapDistrictGangnam: { right: 44, top: 328 },
    mapRouteLine: { position: "absolute", height: 5, borderRadius: 3 },
    mapPinWrap: { position: "absolute", alignItems: "center" },
    mapPinLabel: {
        minHeight: 25,
        paddingHorizontal: 8,
        borderRadius: 8,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000000",
        shadowOpacity: 0.10,
        shadowRadius: 5,
        shadowOffset: { width: 0, height: 2 },
    },
    mapPinLabelText: { fontSize: 11, lineHeight: 15, fontWeight: "700" },
    mapPin: {
        width: 22,
        height: 22,
        marginTop: 3,
        borderRadius: 11,
        borderWidth: 3,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000000",
        shadowOpacity: 0.16,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
    },
    selectedMapLeg: {
        position: "absolute",
        left: 20,
        top: 138,
        height: 32,
        paddingHorizontal: 11,
        borderRadius: 16,
        borderWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    selectedMapLegDot: { width: 7, height: 7, borderRadius: 4 },
    selectedMapLegText: { fontSize: 12, lineHeight: 16, fontWeight: "700" },
    header: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 10,
        borderBottomWidth: StyleSheet.hairlineWidth,
        shadowColor: "#000000",
        shadowOpacity: 0.04,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
    },
    headerMainRow: { height: 56, paddingHorizontal: 10, flexDirection: "row", alignItems: "center" },
    headerIconButton: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center" },
    headerTitleArea: { flex: 1, minWidth: 0, paddingHorizontal: 2 },
    headerActionRow: { flexDirection: "row", alignItems: "center" },
    headerCategoryRow: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 1 },
    categoryDot: { width: 7, height: 7, borderRadius: 4 },
    headerCategory: { fontSize: 10, lineHeight: 13, fontWeight: "600" },
    improvedHeaderTitle: { fontSize: 16, lineHeight: 21, fontWeight: "700", letterSpacing: -0.2 },
    currentKindRow: { flexDirection: "row", alignItems: "center", gap: 4 },
    currentKindText: { fontSize: 10, lineHeight: 13, fontWeight: "800" },
    currentHeaderTitle: { marginTop: 1, fontSize: 16, lineHeight: 21, fontWeight: "900" },
    currentRouteBar: {
        height: 56,
        marginHorizontal: 16,
        borderTopWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    currentRouteBarText: { flex: 1, minWidth: 0, fontSize: 13, lineHeight: 18, fontWeight: "900" },
    routeMetaText: { fontSize: 11, lineHeight: 15, fontWeight: "600" },
    currentMemoButton: {
        position: "absolute",
        left: 16,
        zIndex: 9,
        height: 42,
        paddingHorizontal: 13,
        borderRadius: 21,
        borderWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        shadowColor: "#000000",
        shadowOpacity: 0.10,
        shadowRadius: 7,
        shadowOffset: { width: 0, height: 3 },
    },
    currentLocationButton: {
        position: "absolute",
        right: 16,
        zIndex: 9,
        height: 42,
        paddingHorizontal: 13,
        borderRadius: 21,
        borderWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        shadowColor: "#000000",
        shadowOpacity: 0.10,
        shadowRadius: 7,
        shadowOffset: { width: 0, height: 3 },
    },
    improvedMapButton: {
        position: "absolute",
        right: 16,
        zIndex: 9,
        width: 44,
        height: 44,
        borderRadius: 22,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000000",
        shadowOpacity: 0.10,
        shadowRadius: 7,
        shadowOffset: { width: 0, height: 3 },
    },
    mapPillText: { fontSize: 11, lineHeight: 15, fontWeight: "800" },
    sheet: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 12,
        borderTopLeftRadius: 26,
        borderTopRightRadius: 26,
        borderWidth: StyleSheet.hairlineWidth,
        borderBottomWidth: 0,
        overflow: "hidden",
        shadowColor: "#000000",
        shadowOpacity: 0.13,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: -5 },
    },
    handleHitArea: { height: 44, alignItems: "center", justifyContent: "center" },
    handle: { width: 34, height: 4, borderRadius: 2 },
    currentCompact: { flex: 1, paddingHorizontal: 20 },
    smallLabelRow: { flexDirection: "row", alignItems: "center", gap: 5 },
    currentSmallLabel: { fontSize: 10, lineHeight: 14, fontWeight: "800" },
    currentCountdown: { marginTop: 1, fontSize: 24, lineHeight: 29, fontWeight: "900" },
    currentCompactTrailing: { position: "absolute", right: 20, top: 10, alignItems: "flex-end", gap: 8 },
    currentCompactDate: { fontSize: 10, lineHeight: 14, fontWeight: "700" },
    currentStatusLine: { marginTop: 6, flexDirection: "row", alignItems: "center", gap: 5 },
    currentStatusText: { fontSize: 10, lineHeight: 14, fontWeight: "700" },
    currentExpandedContent: { paddingHorizontal: 20, paddingBottom: 22 },
    currentStatusSection: { paddingBottom: 12, borderBottomWidth: StyleSheet.hairlineWidth },
    currentStatusTopRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
    currentHeroValue: { marginTop: 2, fontSize: 28, lineHeight: 34, fontWeight: "900" },
    currentDepartureButton: { minWidth: 96, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center", paddingHorizontal: 13 },
    currentDepartureButtonText: { fontSize: 12, lineHeight: 16, fontWeight: "900" },
    currentDateText: { marginTop: 3, fontSize: 11, lineHeight: 15, fontWeight: "700" },
    currentDepartureHint: { marginTop: 5, fontSize: 11, lineHeight: 15, fontWeight: "800" },
    participantRow: { minHeight: 48, marginTop: 10, paddingTop: 9, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    participantTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    participantTitle: { fontSize: 11, lineHeight: 15, fontWeight: "800" },
    participantMetaRow: { flexDirection: "row", alignItems: "center", gap: 4 },
    avatar: { width: 26, height: 26, borderRadius: 13, alignItems: "center", justifyContent: "center", marginLeft: -7 },
    avatarText: { fontSize: 9, lineHeight: 12, fontWeight: "900" },
    participantMeta: { marginLeft: 3, fontSize: 10, lineHeight: 14, fontWeight: "700" },
    currentRouteSection: { paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth },
    currentRouteTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    currentLiveRow: { flexDirection: "row", alignItems: "center", gap: 5 },
    liveDot: { width: 6, height: 6, borderRadius: 3 },
    currentRouteMeta: { fontSize: 10, lineHeight: 14, fontWeight: "700" },
    currentRouteTitle: { marginTop: 2, fontSize: 18, lineHeight: 23, fontWeight: "900" },
    currentRouteDurationRow: { flexDirection: "row", alignItems: "center", gap: 8 },
    currentRouteDuration: { fontSize: 26, lineHeight: 31, fontWeight: "900" },
    currentMapIconButton: { width: 38, height: 38, borderRadius: 19, alignItems: "center", justifyContent: "center" },
    progressWrap: { height: 6, marginTop: 12, borderRadius: 3, flexDirection: "row", gap: 2, overflow: "hidden" },
    progressPiece: { height: 6, borderRadius: 3 },
    progressWalkStart: { flex: 0.5 },
    progressLine4: { flex: 3.2 },
    progressLine2: { flex: 2.2 },
    progressWalkEnd: { flex: 0.4 },
    currentTimelineHeader: { height: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    currentTimelineTitle: { fontSize: 13, lineHeight: 18, fontWeight: "900" },
    currentTimelineTime: { fontSize: 10, lineHeight: 14, fontWeight: "800" },
    currentMiniTimeline: { minHeight: 52, paddingHorizontal: 4, flexDirection: "row", alignItems: "center", gap: 10 },
    currentMiniTimelineText: { flex: 1, minWidth: 0, fontSize: 12, lineHeight: 17, fontWeight: "800" },
    currentMiniTimelineMeta: { fontSize: 10, lineHeight: 14, fontWeight: "700" },
    currentLineBadge: { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center" },
    currentLineBadgeText: { color: "#FFFFFF", fontSize: 10, lineHeight: 13, fontWeight: "900" },
    improvedCompact: { flex: 1, paddingHorizontal: 20 },
    sheetRouteIdentity: { minHeight: 31, flexDirection: "row", alignItems: "center", gap: 6 },
    sheetRouteIdentityCompact: { minHeight: 44, gap: 8 },
    sheetRouteIdentityExpanded: { marginTop: -3, marginBottom: 3 },
    sheetRouteIdentityTitle: { flex: 1, minWidth: 0, fontSize: 12, lineHeight: 16, fontWeight: "700" },
    sheetRouteIdentityMeta: { fontSize: 11, lineHeight: 15, fontWeight: "500" },
    compactDepartureAction: {
        height: 38,
        paddingHorizontal: 11,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 5,
    },
    compactDepartureActionText: { fontSize: 11, lineHeight: 15, fontWeight: "700" },
    improvedCompactTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    improvedEyebrow: { fontSize: 11, lineHeight: 15, fontWeight: "700", letterSpacing: -0.1 },
    improvedTimeRow: { marginTop: 1, flexDirection: "row", alignItems: "center", gap: 8 },
    improvedCompactTime: { fontSize: 25, lineHeight: 31, fontWeight: "800", letterSpacing: -0.5 },
    improvedHeroTime: { fontSize: 28, lineHeight: 34, fontWeight: "800", letterSpacing: -0.6 },
    timeLeftChip: { minHeight: 25, paddingHorizontal: 9, borderRadius: 13, alignItems: "center", justifyContent: "center" },
    timeLeftChipText: { fontSize: 11, lineHeight: 15, fontWeight: "700" },
    improvedArrivalLine: { marginTop: 4, fontSize: 12, lineHeight: 17, fontWeight: "500" },
    improvedCompactFacts: { marginTop: 8, fontSize: 11, lineHeight: 15, fontWeight: "500" },
    previewActionPressed: { opacity: 0.65 },
    departedInline: { marginTop: 8, flexDirection: "row", alignItems: "center", gap: 5 },
    departedInlineText: { fontSize: 11, lineHeight: 15, fontWeight: "600" },
    improvedExpandedContent: { paddingHorizontal: 20, paddingBottom: 24 },
    improvedHero: { paddingBottom: 14, borderBottomWidth: StyleSheet.hairlineWidth },
    improvedHeroTop: { flexDirection: "row", alignItems: "center", gap: 12 },
    improvedHeroCopy: { flex: 1, minWidth: 0 },
    improvedDepartureButton: { minWidth: 100, height: 44, paddingHorizontal: 13, borderRadius: 14, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
    improvedDepartureButtonText: { fontSize: 12, lineHeight: 16, fontWeight: "700" },
    improvedRouteFacts: { marginTop: 13, flexDirection: "row", alignItems: "center", gap: 8 },
    improvedRouteFact: { fontSize: 11, lineHeight: 15, fontWeight: "600" },
    factDivider: { width: 1, height: 11 },
    improvedExistingRouteBar: { marginTop: 12 },
    sharedPeopleSection: { paddingVertical: 14, borderBottomWidth: StyleSheet.hairlineWidth },
    sharedPeopleHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    sharedPeopleTitleRow: { flexDirection: "row", alignItems: "center", gap: 7 },
    sharedPeopleTitle: { fontSize: 13, lineHeight: 18, fontWeight: "700", letterSpacing: -0.1 },
    sharedPeopleSummary: { fontSize: 11, lineHeight: 15, fontWeight: "600" },
    sharedPeopleRow: { marginTop: 12, flexDirection: "row", alignItems: "center", gap: 10 },
    sharedPerson: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 7 },
    sharedPersonAvatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "transparent",
        alignItems: "center",
        justifyContent: "center",
    },
    sharedPersonAvatarText: { fontSize: 10, lineHeight: 14, fontWeight: "800" },
    sharedPersonBell: {
        position: "absolute",
        right: -3,
        bottom: -2,
        width: 14,
        height: 14,
        borderRadius: 7,
        alignItems: "center",
        justifyContent: "center",
    },
    sharedPersonCopy: { flex: 1, minWidth: 0 },
    sharedPersonName: { fontSize: 11, lineHeight: 15, fontWeight: "700" },
    sharedPersonStatus: { marginTop: 1, fontSize: 9, lineHeight: 13, fontWeight: "600" },
    improvedTimelineHeader: {
        minHeight: 38,
        marginTop: 12,
        paddingHorizontal: 2,
        paddingBottom: 8,
        borderBottomWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    improvedSectionTitle: { fontSize: 13, lineHeight: 18, fontWeight: "900", letterSpacing: 0 },
    improvedSectionMeta: { flexShrink: 1, fontSize: 10, lineHeight: 14, fontWeight: "800", textAlign: "right" },
    scheduleInfoDisclosure: { minHeight: 54, marginTop: 8, paddingHorizontal: 4, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", gap: 8 },
    scheduleInfoTitleRow: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 7 },
    scheduleInfoTitle: { fontSize: 13, lineHeight: 18, fontWeight: "700" },
    scheduleInfoSummary: { fontSize: 11, lineHeight: 15, fontWeight: "500" },
    scheduleInfoBody: { marginBottom: 8, padding: 12, borderRadius: 12, gap: 5 },
    scheduleInfoBodyText: { fontSize: 11, lineHeight: 16, fontWeight: "500" },
    routeEditButton: { minHeight: 44, alignItems: "center", justifyContent: "center" },
    routeEditButtonText: { fontSize: 12, lineHeight: 16, fontWeight: "700" },
});

export default styles;
