import { StyleSheet } from "react-native";

/** notifications 화면의 정적 시각 규칙입니다. 화면 로직과 독립적으로 조정할 수 있도록 분리했습니다. */
const styles = StyleSheet.create({
    screen: {
        flex: 1,
    },
    header: {
        height: 58,
        paddingHorizontal: 12,
        borderBottomWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "center",
    },
    headerIconButton: {
        width: 42,
        height: 42,
        alignItems: "center",
        justifyContent: "center",
    },
    headerTitleGroup: {
        minWidth: 0,
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    headerTitle: {
        fontSize: 22,
        lineHeight: 28,
        fontWeight: "800",
        letterSpacing: 0,
    },
    headerCount: {
        minWidth: 22,
        height: 20,
        paddingHorizontal: 6,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
    },
    headerCountText: {
        color: "#FFFFFF",
        fontSize: 11,
        lineHeight: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    markAllButton: {
        minWidth: 86,
        height: 42,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-end",
        gap: 5,
    },
    markAllText: {
        fontSize: 14,
        fontWeight: "700",
        letterSpacing: 0,
    },
    pressed: {
        opacity: 0.54,
    },
    filterBar: {
        height: 42,
        marginHorizontal: 16,
        marginTop: 14,
        marginBottom: 8,
        padding: 3,
        borderRadius: 8,
        flexDirection: "row",
    },
    filterButton: {
        flex: 1,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: "transparent",
        borderRadius: 6,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 7,
    },
    filterText: {
        fontSize: 14,
        fontWeight: "700",
        letterSpacing: 0,
    },
    filterDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    listContent: {
        paddingHorizontal: 16,
    },
    emptyListContent: {
        flexGrow: 1,
    },
    notificationRow: {
        minHeight: 88,
        paddingVertical: 16,
        paddingHorizontal: 10,
        borderBottomWidth: StyleSheet.hairlineWidth,
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 12,
    },
    rowIcon: {
        width: 40,
        height: 40,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        flexShrink: 0,
    },
    rowContent: {
        flex: 1,
        minWidth: 0,
    },
    rowTitleLine: {
        minWidth: 0,
        flexDirection: "row",
        alignItems: "baseline",
        gap: 10,
    },
    rowTitle: {
        flex: 1,
        minWidth: 0,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "600",
        letterSpacing: 0,
    },
    rowTitleUnread: {
        fontWeight: "800",
    },
    rowTime: {
        flexShrink: 0,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "500",
        letterSpacing: 0,
    },
    rowBody: {
        marginTop: 4,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "400",
        letterSpacing: 0,
    },
    unreadDot: {
        width: 7,
        height: 7,
        borderRadius: 4,
        marginTop: 7,
        flexShrink: 0,
    },
    errorBanner: {
        minHeight: 48,
        marginTop: 8,
        marginBottom: 4,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 8,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    errorText: {
        flex: 1,
        fontSize: 13,
        lineHeight: 18,
        letterSpacing: 0,
    },
    retryText: {
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 0,
    },
    emptyState: {
        flex: 1,
        minHeight: 300,
        paddingHorizontal: 28,
        alignItems: "center",
        justifyContent: "center",
    },
    emptyIcon: {
        width: 56,
        height: 56,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 18,
    },
    emptyTitle: {
        fontSize: 17,
        lineHeight: 23,
        fontWeight: "800",
        textAlign: "center",
        letterSpacing: 0,
    },
    emptyCaption: {
        marginTop: 7,
        maxWidth: 280,
        fontSize: 14,
        lineHeight: 20,
        textAlign: "center",
        letterSpacing: 0,
    },
    loadMoreButton: {
        height: 46,
        marginTop: 18,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 8,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
    },
    loadMoreText: {
        fontSize: 14,
        fontWeight: "700",
        letterSpacing: 0,
    },
});

export default styles;
