import { StyleSheet } from "react-native";

/** 경로 선택 화면의 favorites 영역 정적 스타일입니다. */
const favoritesStyles = {
    searchModeSectionHeader: {
        minHeight: 34,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        marginBottom: 4,
    },
    searchModeSectionTitle: {
        fontSize: 14,
        fontWeight: "900",
    },
    searchModeEditText: {
        fontSize: 13,
        fontWeight: "800",
    },
    favoriteManageButton: {
        minHeight: 34,
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        paddingHorizontal: 4,
    },
    favoriteFilterScroll: {
        marginBottom: 6,
    },
    favoriteFilterContent: {
        gap: 8,
        paddingHorizontal: 20,
        paddingBottom: 2,
    },
    favoriteFilterChip: {
        position: "relative",
        minHeight: 34,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 999,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        paddingHorizontal: 13,
        paddingVertical: 7,
        overflow: "hidden",
    },
    favoriteFilterChipText: {
        fontSize: 12,
        fontWeight: "800",
    },
    favoriteFilterIndicator: {
        position: "absolute",
        left: 12,
        right: 12,
        bottom: 1,
        height: 2,
        borderRadius: 999,
    },
    favoritePanelClip: {
        overflow: "hidden",
    },
    favoriteCategoryDot: {
        width: 8,
        height: 8,
        borderRadius: 999,
    },
    favoriteTitleRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    favoriteTitle: {
        flex: 1,
        minWidth: 0,
    },
    defaultOriginBadge: {
        borderRadius: 999,
        paddingHorizontal: 7,
        paddingVertical: 2,
    },
    defaultOriginBadgeText: {
        fontSize: 10,
        fontWeight: "900",
    },
    favoriteMetaRow: {
        marginTop: 3,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
    favoriteMetaText: {
        flex: 1,
        minWidth: 0,
        marginTop: 0,
    },
    favoriteRowActions: {
        flexDirection: "row",
        alignItems: "center",
    },
    favoriteEmptyRow: {
        minHeight: 48,
        justifyContent: "center",
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
    favoriteLoadErrorRow: {
        minHeight: 52,
        marginHorizontal: 20,
        marginBottom: 10,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    favoriteLoadErrorText: {
        flex: 1,
        minWidth: 0,
        fontSize: 12,
        fontWeight: "700",
        lineHeight: 18,
    },
    favoriteRetryButton: {
        minHeight: 32,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 10,
        paddingHorizontal: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 5,
    },
    favoriteRetryText: {
        fontSize: 12,
        fontWeight: "800",
        lineHeight: 16,
    },
    searchModeResultRow: {
        minHeight: 68,
        flexDirection: "row",
        alignItems: "center",
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        marginHorizontal: 20,
        marginBottom: 8,
        overflow: "hidden",
    },
    searchModeResultMain: {
        flex: 1,
        minWidth: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        paddingLeft: 12,
        paddingRight: 8,
        paddingVertical: 10,
    },
    searchModeRecentRow: {
        minHeight: 58,
        flexDirection: "row",
        alignItems: "center",
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        marginHorizontal: 20,
        marginBottom: 8,
        overflow: "hidden",
    },
    searchModeRecentMain: {
        flex: 1,
        minWidth: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        paddingLeft: 12,
        paddingRight: 8,
        paddingVertical: 10,
    },
    searchModeListIcon: {
        width: 34,
        height: 34,
        borderRadius: 999,
        alignItems: "center",
        justifyContent: "center",
    },
    favoriteListIcon: {
        borderWidth: StyleSheet.hairlineWidth,
    },
    searchModeResultTextWrap: {
        flex: 1,
        minWidth: 0,
    },
    searchModeFavoriteButton: {
        width: 48,
        alignSelf: "stretch",
        alignItems: "center",
        justifyContent: "center",
    },
    searchModeRemoveButton: {
        width: 52,
        alignSelf: "stretch",
        alignItems: "center",
        justifyContent: "center",
    },
    searchModeRemoveText: {
        marginTop: -1,
        fontSize: 24,
        fontWeight: "300",
        lineHeight: 26,
    },
    searchModeEmptyRow: {
        minHeight: 48,
        justifyContent: "center",
        gap: 10,
        paddingHorizontal: 20,
        paddingVertical: 10,
    },
    recentPlaceTitle: {
        fontSize: 13,
        fontWeight: "900",
    },
    recentPlaceAddress: {
        marginTop: 3,
        fontSize: 11,
        fontWeight: "700",
    },
    recentEmptyText: {
        fontSize: 13,
        fontWeight: "700",
    },
    searchingRow: {
        minHeight: 46,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        paddingHorizontal: 14,
    },
    searchingText: {
        fontSize: 13,
        fontWeight: "700",
    },
    searchResultTitle: {
        fontSize: 13,
        fontWeight: "900",
    },
    searchResultCategory: {
        marginTop: 2,
        color: "#1B9B50",
        fontSize: 11,
        fontWeight: "800",
    },
    searchResultAddress: {
        marginTop: 3,
        fontSize: 11,
        fontWeight: "600",
    },
    favoriteModalRoot: {
        flex: 1,
        justifyContent: "flex-end",
    },
    favoriteModalBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0, 0, 0, 0.46)",
    },
    favoriteSheet: {
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        borderWidth: StyleSheet.hairlineWidth,
        maxHeight: "92%",
        paddingHorizontal: 18,
        paddingTop: 10,
        gap: 14,
    },
    favoriteSheetScroll: {
        flexShrink: 1,
    },
    favoriteSheetScrollContent: {
        gap: 14,
        paddingBottom: 4,
    },
    favoriteSheetHandle: {
        alignSelf: "center",
        width: 48,
        height: 5,
        borderRadius: 999,
        marginBottom: 2,
    },
    favoriteSheetHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    favoriteSheetTitle: {
        fontSize: 17,
        fontWeight: "900",
        lineHeight: 22,
    },
    favoriteSheetSubtitle: {
        marginTop: 2,
        fontSize: 12,
        fontWeight: "700",
        lineHeight: 16,
    },
    favoriteSheetCloseButton: {
        width: 32,
        height: 32,
        borderRadius: 999,
        alignItems: "center",
        justifyContent: "center",
    },
    favoriteSheetCloseText: {
        marginTop: -2,
        fontSize: 24,
        fontWeight: "500",
        lineHeight: 28,
    },
    favoritePlaceBox: {
        minHeight: 58,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 14,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    favoritePlaceTextWrap: {
        flex: 1,
        minWidth: 0,
    },
    favoritePlaceName: {
        fontSize: 14,
        fontWeight: "900",
    },
    favoritePlaceAddress: {
        marginTop: 3,
        fontSize: 11,
        fontWeight: "700",
    },
    favoriteSectionHeaderRow: {
        minHeight: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    favoriteSectionLabel: {
        fontSize: 13,
        fontWeight: "900",
    },
    favoriteCategoryWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    favoriteCategoryChip: {
        minHeight: 36,
        maxWidth: "100%",
        borderWidth: 1,
        borderRadius: 999,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        paddingHorizontal: 12,
    },
    favoriteCategoryChipText: {
        maxWidth: 180,
        fontSize: 12,
        fontWeight: "900",
    },
    favoriteCategorySwatch: {
        width: 9,
        height: 9,
        borderRadius: 999,
    },
    favoriteCategoryError: {
        marginTop: -5,
        fontSize: 11,
        fontWeight: "700",
    },
    favoriteNewCategoryBox: {
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 16,
        padding: 12,
        gap: 10,
    },
    favoriteNewCategoryInput: {
        height: 40,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 12,
        paddingHorizontal: 12,
        fontSize: 13,
        fontWeight: "800",
    },
    favoriteColorRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    favoriteColorButton: {
        width: 32,
        height: 32,
        borderRadius: 999,
        borderWidth: 2,
        alignItems: "center",
        justifyContent: "center",
    },
    favoriteColorSwatch: {
        width: 24,
        height: 24,
        borderRadius: 999,
    },
    favoriteCreateCategoryButton: {
        height: 40,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    favoriteCreateCategoryText: {
        fontSize: 12,
        fontWeight: "900",
    },
    favoriteSaveButton: {
        height: 46,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    favoriteSaveButtonText: {
        fontSize: 14,
        fontWeight: "900",
    },
} as const;

export default favoritesStyles;
