import { StyleSheet } from "react-native";

/** ShareInvitationSheet 화면의 정적 시각 규칙입니다. 화면 로직과 독립적으로 조정할 수 있도록 분리했습니다. */
const styles = StyleSheet.create({
    backdrop: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.34)",
    },
    keyboardAvoidingView: {
        flex: 1,
        justifyContent: "flex-end",
    },
    sheet: {
        maxHeight: "88%",
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        borderWidth: 1,
        paddingHorizontal: 18,
        shadowColor: "#000000",
        shadowOpacity: 0.16,
        shadowRadius: 24,
        shadowOffset: { width: 0, height: -10 },
        elevation: 20,
        overflow: "hidden",
    },
    handleRow: {
        height: 26,
        alignItems: "center",
        justifyContent: "center",
    },
    handle: {
        width: 42,
        height: 4,
        borderRadius: 2,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        paddingBottom: 14,
    },
    modeSegment: {
        height: 42,
        borderRadius: 10,
        padding: 3,
        flexDirection: "row",
        gap: 3,
        marginBottom: 14,
    },
    modeIndicator: {
        position: "absolute",
        top: 3,
        bottom: 3,
        left: 3,
        borderRadius: 8,
        borderWidth: 1,
    },
    modeOption: {
        flex: 1,
        minWidth: 0,
        zIndex: 1,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "transparent",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
    },
    modeOptionText: {
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 0,
    },
    resourceIcon: {
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: "center",
        justifyContent: "center",
    },
    headerText: {
        flex: 1,
        minWidth: 0,
    },
    eyebrow: {
        fontSize: 12,
        fontWeight: "800",
        letterSpacing: 0,
    },
    title: {
        marginTop: 2,
        fontSize: 18,
        fontWeight: "800",
        letterSpacing: 0,
    },
    subtitle: {
        marginTop: 3,
        fontSize: 13,
        fontWeight: "600",
        letterSpacing: 0,
    },
    closeButton: {
        width: 38,
        height: 38,
        borderRadius: 19,
        alignItems: "center",
        justifyContent: "center",
    },
    content: {
        gap: 14,
        paddingBottom: 14,
    },
    contentScroll: {
        flexShrink: 1,
        minHeight: 0,
    },
    modeContent: {
        gap: 14,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    segmentRow: {
        flexDirection: "row",
        gap: 8,
    },
    permissionOption: {
        flex: 1,
        minHeight: 86,
        borderWidth: 1,
        borderRadius: 14,
        paddingHorizontal: 10,
        paddingVertical: 11,
        justifyContent: "space-between",
    },
    permissionLabel: {
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    permissionDescription: {
        marginTop: 7,
        fontSize: 11,
        fontWeight: "600",
        lineHeight: 15,
        letterSpacing: 0,
    },
    contentModeRow: {
        flexDirection: "row",
        gap: 8,
    },
    contentModeOption: {
        flex: 1,
        minWidth: 0,
        minHeight: 52,
        borderWidth: 1,
        borderRadius: 10,
        paddingHorizontal: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 7,
    },
    contentModeLabel: {
        flexShrink: 1,
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "800",
        letterSpacing: 0,
    },
    optionGrid: {
        gap: 12,
    },
    directTargetBlock: {
        gap: 8,
        paddingBottom: 4,
    },
    targetInputShell: {
        height: 50,
        borderRadius: 10,
        borderWidth: 1,
        paddingHorizontal: 13,
        flexDirection: "row",
        alignItems: "center",
        gap: 9,
    },
    targetInput: {
        flex: 1,
        minWidth: 0,
        height: "100%",
        paddingVertical: 0,
        fontSize: 14,
        fontWeight: "700",
        letterSpacing: 0,
    },
    directSuccess: {
        minHeight: 42,
        borderRadius: 8,
        paddingHorizontal: 11,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    directSuccessText: {
        flex: 1,
        minWidth: 0,
        fontSize: 13,
        lineHeight: 17,
        fontWeight: "800",
        letterSpacing: 0,
    },
    errorText: {
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "700",
        letterSpacing: 0,
    },
    optionBlock: {
        gap: 8,
    },
    chipRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    chip: {
        minWidth: 72,
        height: 36,
        borderWidth: 1,
        borderRadius: 18,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 12,
    },
    chipText: {
        fontSize: 13,
        fontWeight: "800",
        letterSpacing: 0,
    },
    generatedLink: {
        minHeight: 48,
        borderWidth: 1,
        borderRadius: 14,
        flexDirection: "row",
        alignItems: "center",
        gap: 9,
        paddingHorizontal: 12,
    },
    generatedLinkText: {
        flex: 1,
        minWidth: 0,
        fontSize: 13,
        fontWeight: "700",
        letterSpacing: 0,
    },
    invitationPanel: {
        borderWidth: 1,
        borderRadius: 16,
        padding: 13,
        gap: 10,
    },
    invitationHeader: {
        minHeight: 22,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    invitationRetry: {
        minHeight: 44,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    invitationSummary: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    statusDot: {
        width: 9,
        height: 9,
        borderRadius: 5,
    },
    invitationSummaryText: {
        flex: 1,
        minWidth: 0,
    },
    revokeButton: {
        minHeight: 38,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    revokeButtonText: {
        color: "#DC2626",
        fontSize: 12,
        fontWeight: "900",
    },
    invitationTitle: {
        fontSize: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    helperText: {
        marginTop: 2,
        fontSize: 12,
        fontWeight: "600",
        lineHeight: 17,
        letterSpacing: 0,
    },
    primaryButton: {
        height: 50,
        borderRadius: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
    },
    primaryButtonText: {
        color: "#FFFFFF",
        fontSize: 15,
        fontWeight: "800",
        letterSpacing: 0,
    },
});

export default styles;
