import { StyleSheet } from "react-native";

/** places 화면의 정적 시각 규칙입니다. 화면 로직과 독립적으로 조정할 수 있도록 분리했습니다. */
const styles = StyleSheet.create({
    root: { flex: 1 },
    header: {
        minHeight: 76,
        paddingHorizontal: 16,
        paddingBottom: 10,
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    headerButtonGlass: { width: 44, height: 44, borderRadius: 22, borderWidth: 1 },
    headerButton: { flex: 1, alignItems: "center", justifyContent: "center" },
    headerTitleWrap: { flex: 1, minWidth: 0, alignItems: "center" },
    headerTitle: { fontSize: 18, fontWeight: "900" },
    headerCaption: { marginTop: 2, fontSize: 10, fontWeight: "700" },
    content: { paddingHorizontal: 18, paddingTop: 10, gap: 26 },
    section: { gap: 10 },
    sectionHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
    sectionTitle: { paddingHorizontal: 2, fontSize: 12, fontWeight: "900" },
    sectionCaption: { marginTop: 3, paddingHorizontal: 2, fontSize: 11, fontWeight: "700" },
    selectedCategoryTitle: { paddingHorizontal: 2, fontSize: 20, fontWeight: "900" },
    flexText: { flex: 1, minWidth: 0 },
    errorCard: { borderWidth: 1, borderRadius: 16, padding: 14, flexDirection: "row", alignItems: "center", gap: 11 },
    categoryTabs: { gap: 8, paddingRight: 4 },
    categoryTab: { position: "relative", minHeight: 48, maxWidth: 190, paddingHorizontal: 10, borderWidth: 1, borderRadius: 16, flexDirection: "row", alignItems: "center", gap: 7, overflow: "hidden" },
    categoryTabMark: { width: 28, height: 28, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    categoryTabDot: { width: 10, height: 10, borderRadius: 5 },
    categoryTabLabel: { maxWidth: 94, fontSize: 13, fontWeight: "900" },
    categoryTabCount: { minWidth: 22, height: 22, paddingHorizontal: 5, borderRadius: 11, alignItems: "center", justifyContent: "center" },
    categoryTabCountText: { fontSize: 10, fontWeight: "900" },
    categoryTabIndicator: { position: "absolute", left: 10, right: 10, bottom: 2, height: 2, borderRadius: 999 },
    addCategoryTab: { minHeight: 48, paddingHorizontal: 12, borderWidth: 1, borderStyle: "dashed", borderRadius: 16, flexDirection: "row", alignItems: "center", gap: 4 },
    addCategoryTabText: { color: "#2563EB", fontSize: 12, fontWeight: "900" },
    categoryManageBar: { minHeight: 52, paddingHorizontal: 11, borderWidth: 1, borderRadius: 15, flexDirection: "row", alignItems: "center", gap: 8 },
    categoryManageText: { flex: 1, fontSize: 11, fontWeight: "800" },
    defaultCard: { borderWidth: 1, borderRadius: 20, padding: 16, gap: 14 },
    placeMainRow: { flexDirection: "row", alignItems: "center", gap: 12 },
    placeIcon: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center" },
    defaultName: { flexShrink: 1, fontSize: 18, fontWeight: "900" },
    cardTitle: { flexShrink: 1, fontSize: 15, fontWeight: "900" },
    cardCaption: { marginTop: 3, fontSize: 12, lineHeight: 17, fontWeight: "700" },
    badgeRow: { flexDirection: "row", alignItems: "center", gap: 7 },
    defaultBadge: { paddingHorizontal: 7, paddingVertical: 3, borderRadius: 999, backgroundColor: "rgba(37,99,235,0.13)" },
    defaultBadgeText: { color: "#2563EB", fontSize: 10, fontWeight: "900" },
    defaultUsageText: { fontSize: 11, fontWeight: "800" },
    defaultActions: { flexDirection: "row", justifyContent: "flex-end", gap: 8 },
    secondaryButton: { minHeight: 38, paddingHorizontal: 14, borderWidth: 1, borderRadius: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
    secondaryButtonText: { fontSize: 13, fontWeight: "900" },
    emptyDefaultContent: { paddingVertical: 8, alignItems: "center" },
    emptyDefaultIcon: { width: 54, height: 54, borderRadius: 27, alignItems: "center", justifyContent: "center" },
    emptyDefaultTitle: { marginTop: 13, fontSize: 18, fontWeight: "900" },
    emptyDefaultCaption: { marginTop: 6, maxWidth: 310, textAlign: "center", fontSize: 12, lineHeight: 18, fontWeight: "700" },
    primaryButton: { marginTop: 16, minHeight: 44, paddingHorizontal: 18, borderRadius: 14, backgroundColor: "#2563EB", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
    primaryButtonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" },
    smallAddButton: { minHeight: 36, paddingHorizontal: 10, borderRadius: 11, backgroundColor: "rgba(37,99,235,0.10)", flexDirection: "row", alignItems: "center", gap: 3 },
    smallAddButtonText: { color: "#2563EB", fontSize: 12, fontWeight: "900" },
    emptyListCard: { minHeight: 122, borderWidth: 1, borderRadius: 18, padding: 20, alignItems: "center", justifyContent: "center" },
    emptyListTitle: { marginTop: 9, fontSize: 15, fontWeight: "900" },
    placeCard: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 14, paddingTop: 14, overflow: "hidden" },
    categoryPillRow: { marginTop: 7, flexDirection: "row", alignItems: "center", gap: 5 },
    colorDot: { width: 9, height: 9, borderRadius: 5 },
    categoryPillText: { fontSize: 11, fontWeight: "800" },
    cardToolbar: { minHeight: 48, marginTop: 13, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    reorderButtons: { flexDirection: "row", gap: 7 },
    cardActions: { flexDirection: "row", gap: 7 },
    iconAction: { width: 34, height: 34, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    categoryCard: { minHeight: 70, borderWidth: 1, borderRadius: 17, padding: 12, flexDirection: "row", alignItems: "center", gap: 10 },
    categoryIcon: { width: 42, height: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" },
    categoryLargeDot: { width: 16, height: 16, borderRadius: 8 },
    categoryActions: { flexDirection: "row", gap: 5 },
    busyOverlay: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "flex-end", paddingBottom: 34 },
    busyPill: { minHeight: 48, paddingHorizontal: 17, borderRadius: 24, flexDirection: "row", alignItems: "center", gap: 9, shadowColor: "#000", shadowOpacity: 0.18, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 6 },
    busyText: { fontSize: 13, fontWeight: "900" },
    sheetRoot: { flex: 1 },
    sheetHeader: { minHeight: 78, paddingHorizontal: 20, paddingBottom: 14, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", gap: 14 },
    sheetTitle: { fontSize: 21, fontWeight: "900" },
    sheetCaption: { marginTop: 4, fontSize: 12, lineHeight: 17, fontWeight: "700" },
    sheetClose: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" },
    sheetContent: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 44, gap: 24 },
    sheetSection: { gap: 10 },
    sheetSectionTitle: { fontSize: 12, fontWeight: "900" },
    sheetPlaceRow: { minHeight: 66, borderWidth: 1, borderRadius: 15, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 11 },
    selectedText: { color: "#2563EB", fontSize: 11, fontWeight: "900" },
    searchBar: { height: 54, borderWidth: 1, borderRadius: 15, paddingLeft: 14, paddingRight: 5, flexDirection: "row", alignItems: "center", gap: 8 },
    searchInput: { flex: 1, height: "100%", fontSize: 15, fontWeight: "700" },
    searchButton: { width: 43, height: 43, borderRadius: 12, backgroundColor: "#2563EB", alignItems: "center", justifyContent: "center" },
    searchResult: { minHeight: 72, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", gap: 11 },
    searchResultIcon: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" },
    searchGuide: { minHeight: 150, alignItems: "center", justifyContent: "center" },
    searchGuideText: { marginTop: 9, fontSize: 12, fontWeight: "700" },
    editorContent: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 44 },
    inputLabel: { marginBottom: 8, fontSize: 12, fontWeight: "900" },
    editorInput: { height: 52, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, fontSize: 15, fontWeight: "700", marginBottom: 24 },
    choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    choiceChip: { minHeight: 39, paddingHorizontal: 12, borderWidth: 1.5, borderRadius: 13, flexDirection: "row", alignItems: "center", gap: 6 },
    choiceChipText: { fontSize: 13, fontWeight: "800" },
    helperText: { marginTop: 10, fontSize: 11, lineHeight: 16, fontWeight: "700" },
    editorSaveButton: { marginTop: 32, height: 52, borderRadius: 15, backgroundColor: "#2563EB", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 },
    editorSaveText: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },
    colorChoices: { flexDirection: "row", flexWrap: "wrap", gap: 13 },
    colorChoice: { width: 44, height: 44, borderRadius: 22, borderWidth: 3, alignItems: "center", justifyContent: "center" },
});

export default styles;
