import { StyleSheet } from "react-native";

/** ScheduleAgendaCard 화면의 정적 시각 규칙입니다. 화면 로직과 독립적으로 조정할 수 있도록 분리했습니다. */
const styles = StyleSheet.create({
    card: {
        minHeight: 62,
        flexDirection: "row",
        alignItems: "stretch",
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 9,
        overflow: "hidden",
    },
    cardCompact: {
        minHeight: 58,
        borderRadius: 8,
    },
    groupRow: {
        minHeight: 52,
        borderWidth: 0,
        borderRadius: 0,
    },
    categoryRail: {
        width: 3,
        flexShrink: 0,
    },
    categoryRailCompact: {
        width: 2.5,
    },
    categoryRailGroupRow: {
        width: 3,
        marginVertical: 4,
        borderRadius: 2,
    },
    content: {
        flex: 1,
        minWidth: 0,
        justifyContent: "center",
        paddingVertical: 9,
        paddingLeft: 11,
        paddingRight: 3,
    },
    contentCompact: {
        paddingVertical: 7,
        paddingLeft: 10,
        paddingRight: 2,
    },
    contentGroupRow: {
        paddingVertical: 5,
        gap: 1,
    },
    titleRow: {
        minWidth: 0,
        minHeight: 20,
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    titleRowCompact: {
        minHeight: 18,
        gap: 5,
    },
    titleIcon: {
        flexShrink: 0,
    },
    durationBadge: {
        height: 20,
        flexShrink: 0,
        justifyContent: "center",
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 7,
        paddingHorizontal: 6,
    },
    durationBadgeText: {
        fontSize: 10.5,
        lineHeight: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    statusBadge: {
        height: 20,
        flexShrink: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 3,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 10,
        paddingHorizontal: 6,
    },
    statusBadgeText: {
        fontSize: 10.5,
        lineHeight: 14,
        fontWeight: "700",
        letterSpacing: 0,
    },
    routeBadge: {
        height: 21,
        flexShrink: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 3,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 11,
        paddingHorizontal: 6,
    },
    routeBadgeText: {
        fontSize: 10.5,
        lineHeight: 14,
        fontWeight: "800",
    },
    title: {
        flex: 1,
        minWidth: 0,
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "800",
        letterSpacing: 0,
    },
    titleCompact: {
        fontSize: 14,
        lineHeight: 18,
        fontWeight: "700",
    },
    metaRow: {
        minWidth: 0,
        minHeight: 17,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    detailContextRow: {
        minWidth: 0,
        minHeight: 18,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
    detailContextText: {
        flex: 1,
        minWidth: 0,
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "600",
        letterSpacing: 0,
    },
    detailTravelText: {
        fontWeight: "800",
    },
    routeStatusBadge: {
        height: 20,
        flexShrink: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 3,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 7,
        paddingHorizontal: 6,
    },
    routeStatusBadgeText: {
        fontSize: 10.5,
        lineHeight: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
    multiDayRow: {
        minWidth: 0,
        minHeight: 17,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
    multiDayStay: {
        flexShrink: 0,
        fontSize: 12.5,
        lineHeight: 17,
        fontWeight: "800",
        letterSpacing: 0,
    },
    multiDaySeparator: {
        width: 2,
        height: 2,
        borderRadius: 1,
        flexShrink: 0,
        opacity: 0.72,
    },
    multiDayRange: {
        flex: 1,
        minWidth: 0,
        fontSize: 11.5,
        lineHeight: 16,
        fontWeight: "600",
        letterSpacing: 0,
    },
    metaRowCompact: {
        minHeight: 15,
        gap: 9,
    },
    time: {
        flexShrink: 0,
        fontSize: 12.5,
        lineHeight: 17,
        fontWeight: "700",
        letterSpacing: 0,
    },
    location: {
        flex: 1,
        minWidth: 0,
        fontSize: 12.5,
        lineHeight: 17,
        fontWeight: "600",
        letterSpacing: 0,
    },
    metaTextCompact: {
        fontSize: 11.5,
        lineHeight: 15,
        fontWeight: "600",
    },
    travelRow: {
        minWidth: 0,
        minHeight: 17,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
    travelRowCompact: {
        minHeight: 15,
        gap: 4,
    },
    travelText: {
        flex: 1,
        minWidth: 0,
        fontSize: 12.5,
        lineHeight: 17,
        fontWeight: "800",
        letterSpacing: 0,
    },
    travelTextCompact: {
        fontSize: 11.5,
        lineHeight: 15,
        fontWeight: "700",
    },
    detailTimeColumn: {
        width: 108,
        flexShrink: 0,
        alignItems: "flex-end",
        justifyContent: "center",
        gap: 1,
        paddingLeft: 6,
        paddingRight: 10,
    },
    detailTimePrimary: {
        width: "100%",
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "700",
        letterSpacing: -0.2,
        textAlign: "right",
    },
    detailTimeSecondary: {
        width: "100%",
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "500",
        letterSpacing: -0.2,
        textAlign: "right",
    },
    chevronColumn: {
        width: 32,
        flexShrink: 0,
        alignItems: "center",
        justifyContent: "center",
    },
    chevronColumnCompact: {
        width: 27,
    },
});

export default styles;
