import { StyleSheet } from "react-native";

import type { QuickScheduleModalStylesOptions } from "../QuickScheduleModal.styles";

/** photo 영역의 정적 스타일을 생성합니다. */
export function createPhotoStyles(options: QuickScheduleModalStylesOptions) {
    const {
        BLUE,
    } = options;
    return StyleSheet.create({
        photoModeContent: {
        marginBottom: 14,
    },
        photoPreviewButton: {
        height: 190,
        borderRadius: 18,
        borderWidth: 1,
        overflow: "hidden",
    },
        photoImageBackdrop: {
        ...StyleSheet.absoluteFillObject,
        width: "100%",
        height: "100%",
        opacity: 0.32,
        transform: [{ scale: 1.08 }],
    },
        photoImageBackdropScrim: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(5,10,18,0.50)",
    },
        photoImageStage: {
        height: "100%",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1,
    },
        photoScanFrame: {
        alignSelf: "center",
        backgroundColor: "#070B13",
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: "rgba(255,255,255,0.16)",
    },
        photoImage: {
        width: "100%",
        height: "100%",
    },
        photoStatusPill: {
        position: "absolute",
        top: 12,
        left: 12,
        maxWidth: 186,
        minHeight: 34,
        borderRadius: 17,
        flexDirection: "row",
        alignItems: "center",
        gap: 7,
        paddingHorizontal: 11,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: "rgba(255,255,255,0.16)",
        zIndex: 3,
    },
        photoStatusText: {
        fontSize: 11,
        lineHeight: 15,
        fontWeight: "800",
    },
        photoChangeButton: {
        position: "absolute",
        right: 12,
        bottom: 12,
        minHeight: 44,
        borderRadius: 22,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        paddingHorizontal: 13,
        backgroundColor: "rgba(8,13,22,0.80)",
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: "rgba(255,255,255,0.18)",
        zIndex: 3,
    },
        photoChangeButtonText: {
        color: "#FFFFFF",
        fontSize: 11,
        lineHeight: 15,
        fontWeight: "800",
    },
        photoEmptyPanel: {
        minHeight: 144,
        borderRadius: 15,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 22,
        paddingVertical: 18,
    },
        photoEmptyIcon: {
        width: 44,
        height: 44,
        borderRadius: 13,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 11,
    },
        photoEmptyTitle: {
        fontSize: 15,
        lineHeight: 20,
        fontWeight: "800",
        textAlign: "center",
    },
        photoEmptyMeta: {
        marginTop: 4,
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "500",
        textAlign: "center",
    },
        photoRemoveButton: {
        position: "absolute",
        top: 12,
        right: 12,
        width: 38,
        height: 38,
        borderRadius: 19,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(8,13,22,0.78)",
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: "rgba(255,255,255,0.18)",
        zIndex: 3,
    },
        photoTranscriptWrap: {
        minHeight: 128,
        marginTop: 12,
        borderRadius: 16,
        borderWidth: 1,
        paddingHorizontal: 13,
        paddingTop: 12,
        paddingBottom: 12,
    },
        photoTranscriptHeader: {
        minHeight: 38,
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
        photoResultIcon: {
        width: 36,
        height: 36,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
        photoResultTitleWrap: {
        flex: 1,
        minWidth: 0,
    },
        photoTranscriptLabel: {
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "800",
    },
        photoResultMeta: {
        marginTop: 1,
        fontSize: 10,
        lineHeight: 14,
        fontWeight: "600",
    },
        photoConfidence: {
        fontSize: 10,
        lineHeight: 14,
        fontWeight: "800",
    },
        truncatedRecognitionBadge: {
        minHeight: 26,
        borderRadius: 13,
        justifyContent: "center",
        paddingHorizontal: 9,
        backgroundColor: "rgba(245,158,11,0.11)",
    },
        truncatedRecognitionText: {
        color: "#F59E0B",
    },
        photoReviewBadge: {
        minHeight: 26,
        borderRadius: 13,
        justifyContent: "center",
        paddingHorizontal: 9,
        backgroundColor: "rgba(245,158,11,0.12)",
    },
        photoReviewBadgeText: {
        color: "#D97706",
        fontSize: 10,
        lineHeight: 14,
        fontWeight: "800",
    },
        photoReadingPlaceholder: {
        minHeight: 72,
        justifyContent: "center",
        gap: 9,
        marginTop: 10,
        paddingHorizontal: 3,
    },
        photoReadingLine: {
        height: 8,
        borderRadius: 4,
        backgroundColor: "rgba(126,145,171,0.14)",
    },
        photoReadingLineLong: {
        width: "92%",
    },
        photoReadingLineMedium: {
        width: "72%",
    },
        photoReadingLineShort: {
        width: "46%",
    },
        photoTranscriptInputWrap: {
        marginTop: 10,
        paddingTop: 9,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: "rgba(126,145,171,0.22)",
    },
        photoTranscriptInputLabel: {
        fontSize: 10,
        lineHeight: 14,
        fontWeight: "800",
    },
        photoTranscriptInput: {
        minHeight: 54,
        maxHeight: 92,
        padding: 0,
        marginTop: 5,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "400",
        textAlignVertical: "top",
    },
        photoRecognitionErrorWrap: {
        marginTop: 10,
        alignItems: "flex-start",
        justifyContent: "center",
        gap: 4,
        borderRadius: 13,
        borderWidth: StyleSheet.hairlineWidth,
        paddingHorizontal: 11,
        paddingTop: 10,
        paddingBottom: 9,
    },
        photoRecognitionErrorTitle: {
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "800",
    },
        photoRecognitionErrorText: {
        fontSize: 11,
        lineHeight: 16,
        fontWeight: "600",
    },
        photoRecognitionRetry: {
        minHeight: 44,
        borderRadius: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 5,
        marginTop: 4,
        paddingHorizontal: 12,
        backgroundColor: "rgba(36,107,254,0.12)",
    },
        photoRecognitionRetryText: {
        color: BLUE,
        fontSize: 12,
        fontWeight: "800",
    },
        lowConfidenceNotice: {
        flexDirection: "row",
        alignItems: "flex-start",
        gap: 5,
        marginTop: 5,
        paddingTop: 7,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: "rgba(245,158,11,0.32)",
    },
        lowConfidenceNoticeText: {
        flex: 1,
        color: "#D97706",
        fontSize: 11,
        lineHeight: 16,
        fontWeight: "700",
    },
    });
}
