import { StyleSheet } from "react-native";

import type { QuickScheduleModalStylesOptions } from "../QuickScheduleModal.styles";

/** voice 영역의 정적 스타일을 생성합니다. */
export function createVoiceStyles(options: QuickScheduleModalStylesOptions) {
    const {
        BLUE,
        VOICE_SPECTRUM_INNER_RADIUS,
        VOICE_SPECTRUM_SIZE,
    } = options;
    return StyleSheet.create({
        voicePanel: {
        minHeight: 322,
        borderRadius: 15,
        borderWidth: 1,
        paddingHorizontal: 13,
        paddingVertical: 13,
        marginBottom: 14,
        overflow: "hidden",
    },
        voiceRecordControl: {
        width: "100%",
        alignItems: "center",
    },
        voiceOrbWrap: {
        width: 150,
        height: 146,
        alignItems: "center",
        justifyContent: "center",
    },
        voiceSpectrum: {
        position: "absolute",
        width: VOICE_SPECTRUM_SIZE,
        height: VOICE_SPECTRUM_SIZE,
        borderRadius: VOICE_SPECTRUM_SIZE / 2,
    },
        voiceSpectrumHaloOuter: {
        position: "absolute",
        width: 112,
        height: 112,
        borderRadius: 56,
        borderWidth: 1,
        borderColor: "rgba(88,215,247,0.48)",
    },
        voiceSpectrumHaloInner: {
        position: "absolute",
        width: 88,
        height: 88,
        borderRadius: 44,
        borderWidth: 1,
        borderColor: "rgba(36,107,254,0.38)",
        backgroundColor: "rgba(36,107,254,0.13)",
        shadowColor: BLUE,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.24,
        shadowRadius: 20,
    },
        voiceSpectrumBarSlot: {
        position: "absolute",
        left: VOICE_SPECTRUM_SIZE / 2 - 1,
        top: 0,
        width: 2,
        height: VOICE_SPECTRUM_SIZE,
        alignItems: "center",
    },
        voiceSpectrumBar: {
        position: "absolute",
        bottom: VOICE_SPECTRUM_SIZE / 2 + VOICE_SPECTRUM_INNER_RADIUS,
        width: 2,
        minHeight: 3,
        borderRadius: 1,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
        voiceOrb: {
        width: 62,
        height: 62,
        borderRadius: 31,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: BLUE,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.14,
        shadowRadius: 18,
    },
        voiceTitle: {
        fontSize: 16,
        lineHeight: 21,
        fontWeight: "800",
        textAlign: "center",
    },
        voiceMeta: {
        marginTop: 3,
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "500",
        textAlign: "center",
    },
        voiceTranscriptWrap: {
        minHeight: 96,
        marginTop: 10,
        borderRadius: 12,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingTop: 9,
        paddingBottom: 8,
    },
        voiceTranscriptHeader: {
        minHeight: 18,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 8,
    },
        voiceTranscriptLabel: {
        fontSize: 11,
        lineHeight: 15,
        fontWeight: "800",
    },
        voiceConfidence: {
        fontSize: 11,
        lineHeight: 15,
        fontWeight: "700",
    },
        voiceTranscriptInput: {
        minHeight: 50,
        maxHeight: 70,
        padding: 0,
        marginTop: 3,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: "400",
        textAlignVertical: "top",
    },
        centerFlow: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 8,
        gap: 10,
    },
        statusIconWrap: {
        width: 72,
        height: 72,
        borderRadius: 36,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 4,
    },
        flowHeadline: {
        fontSize: 17,
        lineHeight: 23,
        fontWeight: "900",
        textAlign: "center",
    },
        flowCaption: {
        fontSize: 13,
        lineHeight: 19,
        fontWeight: "600",
        textAlign: "center",
    },
    });
}
