import { StyleSheet } from "react-native";

import type { ScheduleDetailStylesOptions } from "../schedule-detail.styles";

/** fallback 영역의 정적 스타일을 생성합니다. */
export function createFallbackStyles(options: ScheduleDetailStylesOptions) {
    const {
        APP_ACCENT_BLUE,
    } = options;
    return StyleSheet.create({
        missingScreen: {
        flex: 1,
        paddingHorizontal: 28,
        alignItems: "center",
        justifyContent: "center",
        gap: 12,
    },
        missingTitle: { fontSize: 20, fontWeight: "900", textAlign: "center" },
        missingCaption: { fontSize: 14, fontWeight: "600", lineHeight: 21, textAlign: "center" },
        missingActions: { flexDirection: "row", gap: 10, marginTop: 12 },
        missingSecondaryButton: {
        minHeight: 46,
        paddingHorizontal: 18,
        borderWidth: 1,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
    },
        missingRetryButton: {
        minHeight: 46,
        paddingHorizontal: 18,
        borderRadius: 14,
        backgroundColor: APP_ACCENT_BLUE,
        flexDirection: "row",
        gap: 7,
        alignItems: "center",
        justifyContent: "center",
    },
        missingRetryText: { color: "#FFFFFF", fontWeight: "800" },
        loadingScreen: {
        flex: 1,
    },
        container: { flex: 1 },
        fullMap: { flex: 1 },
        scheduleOnlySurface: {
        flex: 1,
        paddingHorizontal: 20,
        alignItems: "center",
        justifyContent: "center",
    },
        scheduleOnlyCard: {
        width: "100%",
        maxWidth: 420,
        borderWidth: StyleSheet.hairlineWidth,
        borderRadius: 22,
        padding: 18,
        gap: 14,
    },
        scheduleOnlyHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
        scheduleOnlyIcon: {
        width: 42,
        height: 42,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(41,121,255,0.11)",
    },
        scheduleOnlyCopy: {
        flex: 1,
        minWidth: 0,
        gap: 4,
    },
        scheduleOnlyDate: {
        fontSize: 16,
        lineHeight: 22,
        fontWeight: "900",
        letterSpacing: 0,
    },
        scheduleOnlyCategoryRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
        scheduleOnlyCategoryDot: {
        width: 7,
        height: 7,
        borderRadius: 3.5,
    },
        scheduleOnlyCategoryText: {
        flex: 1,
        minWidth: 0,
        fontSize: 12,
        lineHeight: 17,
        fontWeight: "700",
    },
        scheduleOnlyNotes: {
        paddingTop: 13,
        borderTopWidth: StyleSheet.hairlineWidth,
        fontSize: 13,
        lineHeight: 20,
        fontWeight: "600",
    },
        currentLocationButton: {
        position: "absolute",
        right: 16,
        zIndex: 20,
        elevation: 18,
        height: 44,
        borderRadius: 22,
        borderWidth: StyleSheet.hairlineWidth,
        paddingHorizontal: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 7,
        shadowColor: "#000000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.18,
        shadowRadius: 10,
    },
        currentLocationButtonText: {
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "900",
        letterSpacing: 0,
    },
        memoButton: {
        position: "absolute",
        left: 16,
        zIndex: 20,
        elevation: 18,
        height: 44,
        borderRadius: 22,
        borderWidth: StyleSheet.hairlineWidth,
        paddingHorizontal: 14,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        shadowColor: "#000000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.18,
        shadowRadius: 10,
    },
        memoButtonText: {
        fontSize: 12,
        lineHeight: 16,
        fontWeight: "900",
        letterSpacing: 0,
    },
    });
}
