import { StyleSheet } from "react-native";

import type { ScheduleDetailStylesOptions } from "../schedule-detail.styles";

/** header 영역의 정적 스타일을 생성합니다. */
export function createHeaderStyles(options: ScheduleDetailStylesOptions) {
    void options;
    return StyleSheet.create({
        topOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 30,
        elevation: 0,
    },
        topHeaderGlass: {
        minHeight: 112,
        borderTopLeftRadius: 0,
        borderTopRightRadius: 0,
        borderBottomLeftRadius: 24,
        borderBottomRightRadius: 24,
        borderBottomWidth: StyleSheet.hairlineWidth,
        paddingHorizontal: 16,
        paddingBottom: 12,
        overflow: "hidden",
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
    },
        plainPageHeader: {
        minHeight: 0,
        borderBottomLeftRadius: 0,
        borderBottomRightRadius: 0,
        paddingBottom: 10,
    },
        topHeaderRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
        topHeaderIconButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        alignItems: "center",
        justifyContent: "center",
    },
        topHeaderContent: {
        flex: 1,
        minWidth: 0,
    },
        plainTopHeaderContent: {
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 88,
        right: 88,
        alignItems: "center",
        justifyContent: "center",
    },
        topHeaderTitleRow: {
        minWidth: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 9,
    },
        plainTopHeaderTitleRow: {
        width: "100%",
        justifyContent: "center",
    },
        topHeaderKindBadge: {
        minHeight: 18,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
        flexShrink: 0,
    },
        topHeaderKindText: {
        fontSize: 10,
        lineHeight: 14,
        fontWeight: "800",
        letterSpacing: 0,
    },
        topHeaderTitle: {
        flex: 1,
        minWidth: 0,
        fontSize: 17,
        lineHeight: 22,
        fontWeight: "900",
        letterSpacing: 0,
    },
        plainTopHeaderTitle: {
        textAlign: "center",
        fontWeight: "700",
    },
        topHeaderActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 0,
    },
        plainTopHeaderActions: {
        marginLeft: "auto",
    },
        topHeaderRouteBar: {
        minHeight: 42,
        marginTop: 6,
        borderTopWidth: StyleSheet.hairlineWidth,
        paddingTop: 10,
        paddingHorizontal: 4,
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
        topHeaderRouteBarMain: {
        flex: 1,
        minWidth: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 5,
    },
        topHeaderRouteBarText: {
        flex: 1,
        minWidth: 0,
        fontSize: 13,
        lineHeight: 18,
        fontWeight: "900",
        letterSpacing: 0,
    },
        topHeaderTravelPill: {
        maxWidth: 112,
        minHeight: 28,
        alignItems: "center",
        justifyContent: "center",
    },
        topHeaderTravelText: {
        fontSize: 11,
        lineHeight: 15,
        fontWeight: "900",
        letterSpacing: 0,
    },
        departureParticipants: {
        flexDirection: "row",
        flexWrap: "wrap",
        alignItems: "center",
        columnGap: 10,
        rowGap: 12,
        paddingTop: 10,
        paddingBottom: 5,
    },
        departureParticipantItem: {
        minHeight: 44,
        flexBasis: 96,
        flexGrow: 1,
        flexShrink: 0,
        minWidth: 0,
        flexDirection: "row",
        alignItems: "center",
        gap: 7,
    },
        departureParticipantAvatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
    },
        departureParticipantAvatarText: {
        maxWidth: 22,
        fontSize: 10,
        lineHeight: 13,
        fontWeight: "900",
        letterSpacing: 0,
    },
        departureParticipantCheck: {
        position: "absolute",
        right: -2,
        bottom: -1,
        width: 13,
        height: 13,
        borderRadius: 7,
        backgroundColor: "#22C55E",
        alignItems: "center",
        justifyContent: "center",
    },
        departureParticipantBell: {
        position: "absolute",
        right: -3,
        bottom: -2,
        width: 14,
        height: 14,
        borderRadius: 7,
        alignItems: "center",
        justifyContent: "center",
    },
        departureParticipantCopy: {
        flex: 1,
        minWidth: 0,
    },
        departureParticipantName: {
        fontSize: 11,
        lineHeight: 15,
        fontWeight: "800",
        letterSpacing: -0.1,
    },
        departureParticipantStatus: {
        marginTop: 1,
        fontSize: 9,
        lineHeight: 13,
        fontWeight: "700",
        letterSpacing: 0,
    },
    });
}
