import { StyleSheet, Platform } from "react-native";

import type { ScheduleIndexStylesOptions } from "../index.styles";

/** toolbar 영역의 정적 스타일을 생성합니다. */
export function createToolbarStyles(options: ScheduleIndexStylesOptions) {
    const {
        CALENDAR_CONTEXT_HEIGHT,
        LIQUID_TOOLBAR_ACTIONS_WIDTH,
        LIQUID_TOOLBAR_BUTTON_SIZE,
        LIQUID_TOOLBAR_CONTROL_CANVAS_HEIGHT,
        LIQUID_TOOLBAR_SEARCH_HEIGHT,
        LIQUID_TOOLBAR_SLOT_WIDTH,
        LIQUID_YEAR_PILL_WIDTH,
    } = options;
    return StyleSheet.create({
        toolbarLayer: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 40,
        elevation: 40,
        overflow: "visible",
    },
        calendarScopeContextLayer: {
        position: "absolute",
        left: 0,
        right: 0,
        height: CALENDAR_CONTEXT_HEIGHT,
        zIndex: 41,
        elevation: 41,
    },
        categoryErrorLayer: {
        position: "absolute",
        left: 16,
        right: 16,
        zIndex: 39,
        elevation: 39,
    },
        scheduleActionPillLayer: {
        position: "absolute",
        zIndex: 56,
        elevation: 56,
    },
        liquidViewModeControl: {
        position: "absolute",
        height: LIQUID_TOOLBAR_CONTROL_CANVAS_HEIGHT,
        zIndex: 56,
        elevation: 56,
        overflow: "visible",
    },
        searchFieldSeedRow: {
        position: "absolute",
        top: 0,
        right: 0,
        width: LIQUID_TOOLBAR_ACTIONS_WIDTH,
        height: LIQUID_TOOLBAR_BUTTON_SIZE,
        borderRadius: LIQUID_TOOLBAR_BUTTON_SIZE / 2,
        zIndex: 2,
        elevation: 2,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-around",
        paddingHorizontal: 11,
    },
        searchFieldInner: {
        flex: 1,
        minWidth: 0,
        height: "100%",
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        paddingLeft: 20,
        paddingRight: 10,
        zIndex: 3,
        elevation: 3,
    },
        searchHeaderInput: {
        flex: 1,
        minWidth: 0,
        paddingVertical: 0,
        fontSize: 17,
        fontWeight: "600",
        letterSpacing: 0,
    },
        searchHeaderIconButton: {
        width: 38,
        height: 42,
        alignItems: "center",
        justifyContent: "center",
    },
        searchResultsGlass: {
        marginTop: 8,
        borderRadius: 22,
        borderWidth: 1,
        overflow: "hidden",
        maxHeight: 260,
    },
        searchResultsLayer: {
        position: "absolute",
        zIndex: 55,
        elevation: 55,
    },
        toolbarActions: {
        flexDirection: "row",
        alignItems: "center",
        height: LIQUID_TOOLBAR_BUTTON_SIZE,
        borderRadius: LIQUID_TOOLBAR_BUTTON_SIZE / 2,
        borderWidth: Platform.OS === "ios" ? 0 : 1,
        paddingHorizontal: 0,
        overflow: "hidden",
    },
        searchToolbarActions: {
        height: LIQUID_TOOLBAR_SEARCH_HEIGHT,
        borderRadius: LIQUID_TOOLBAR_SEARCH_HEIGHT / 2,
    },
        toolbarActionsPlaceholder: {
        width: LIQUID_TOOLBAR_ACTIONS_WIDTH,
        height: LIQUID_TOOLBAR_BUTTON_SIZE,
    },
        yearGlassMotion: {
        width: "100%",
        height: LIQUID_TOOLBAR_BUTTON_SIZE,
        borderRadius: LIQUID_TOOLBAR_BUTTON_SIZE / 2,
    },
        primaryDatePillHost: {
        height: LIQUID_TOOLBAR_BUTTON_SIZE,
        borderRadius: LIQUID_TOOLBAR_BUTTON_SIZE / 2,
        overflow: "visible",
    },
        yearGlass: {
        width: LIQUID_YEAR_PILL_WIDTH,
        height: LIQUID_TOOLBAR_BUTTON_SIZE,
        borderRadius: LIQUID_TOOLBAR_BUTTON_SIZE / 2,
        borderWidth: Platform.OS === "ios" ? 0 : 1,
        // The native iOS glass pill draws its depth shadow outside the 44pt
        // hit target. Keep that shadow visible while Android retains clipping.
        overflow: Platform.OS === "ios" ? "visible" : "hidden",
    },
        yearGlassSurface: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: LIQUID_TOOLBAR_BUTTON_SIZE / 2,
        borderWidth: Platform.OS === "ios" ? 0 : 1,
        overflow: "hidden",
    },
        yearButton: {
        height: LIQUID_TOOLBAR_BUTTON_SIZE,
        borderRadius: LIQUID_TOOLBAR_BUTTON_SIZE / 2,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingLeft: 8,
        paddingRight: 12,
        gap: 3,
    },
        yearText: {
        fontWeight: "800",
        fontSize: 18,
    },
        iconButton: {
        width: LIQUID_TOOLBAR_SLOT_WIDTH,
        height: LIQUID_TOOLBAR_BUTTON_SIZE,
        alignItems: "center",
        justifyContent: "center",
    },
        iconButtonActive: {
        borderRadius: 18,
        backgroundColor: "rgba(255, 255, 255, 0.035)",
    },
        toolbarDropdownBackdrop: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 42,
        elevation: 42,
        backgroundColor: "transparent",
    },
        liquidToolbarBackdrop: {
        zIndex: 55,
        elevation: 55,
    },
        toolbarDropdown: {
        position: "absolute",
        transformOrigin: "top right",
        zIndex: 45,
        elevation: 45,
    },
        toolbarDropdownPosition: {
        right: 16,
    },
        toolbarDropdownGlass: {
        borderRadius: 26,
        borderWidth: Platform.OS === "ios" ? 0 : 1,
        shadowOffset: { width: 0, height: 18 },
        shadowOpacity: 0.28,
        shadowRadius: 28,
        elevation: 24,
    },
        viewToolbarDropdownGlass: {
        shadowOffset: { width: 0, height: 20 },
        shadowOpacity: 0.36,
        shadowRadius: 34,
        elevation: 26,
    },
        viewDropdownShell: {
        borderRadius: 26,
    },
        viewDropdownShellDark: {
        backgroundColor: "rgba(3,4,8,0.84)",
    },
        viewDropdownShellLight: {
        backgroundColor: "rgba(255,255,255,0.84)",
    },
        dropdownContent: {
        paddingTop: 7,
        paddingBottom: 8,
    },
        viewDropdownContent: {
        paddingTop: 10,
        paddingBottom: 10,
        position: "relative",
        overflow: "hidden",
    },
        viewDropdownReadableScrim: {
        ...StyleSheet.absoluteFillObject,
    },
        viewDropdownReadableScrimDark: {
        backgroundColor: "rgba(3,4,8,0.82)",
    },
        viewDropdownReadableScrimLight: {
        backgroundColor: "rgba(255,255,255,0.86)",
    },
        searchDropdownContent: {
        paddingHorizontal: 14,
    },
        actionDropdownContent: {
        paddingTop: 7,
        paddingBottom: 8,
        paddingHorizontal: 8,
    },
        viewModeRow: {
        minHeight: 47,
        borderRadius: 16,
        marginHorizontal: 8,
        paddingLeft: 10,
        paddingRight: 13,
        flexDirection: "row",
        alignItems: "center",
        gap: 11,
        position: "relative",
        overflow: "hidden",
    },
        viewModeIconGrid: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingHorizontal: 10,
    },
        dayViewModeMenu: {
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
        dayViewModeIconSlot: {
        width: 24,
        alignItems: "center",
        justifyContent: "center",
    },
        viewModeIconOption: {
        width: 40,
        height: 42,
        borderRadius: 17,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: "transparent",
        alignItems: "center",
        justifyContent: "center",
    },
        viewModeSelectedPill: {
        position: "absolute",
        left: 5,
        right: 5,
        top: 5,
        bottom: 5,
        borderRadius: 14,
        borderWidth: StyleSheet.hairlineWidth,
    },
        viewModeSelectedPillDark: {
        backgroundColor: "rgba(255,255,255,0.095)",
        borderColor: "rgba(255,255,255,0.13)",
    },
        viewModeSelectedPillLight: {
        backgroundColor: "rgba(0,0,0,0.052)",
        borderColor: "rgba(0,0,0,0.08)",
    },
        dropdownTitle: {
        fontSize: 17,
        fontWeight: "800",
        letterSpacing: 0,
    },
        dropdownRowDivider: {
        height: StyleSheet.hairlineWidth,
        marginLeft: 50,
        marginRight: 18,
        marginVertical: 5,
    },
        viewDropdownDivider: {
        opacity: 0.34,
    },
        dropdownActionRow: {
        alignSelf: "stretch",
        width: "100%",
        minHeight: 44,
        borderRadius: 15,
        marginHorizontal: 0,
        paddingLeft: 18,
        paddingRight: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 11,
    },
        dropdownActionIconSlot: {
        width: 26,
        alignItems: "center",
        justifyContent: "center",
    },
        inlineSearchField: {
        width: "100%",
        alignSelf: "stretch",
        height: 46,
        borderRadius: 23,
        borderWidth: StyleSheet.hairlineWidth,
        paddingLeft: 14,
        paddingRight: 12,
        flexDirection: "row",
        alignItems: "center",
        gap: 9,
    },
        inlineSearchInput: {
        flex: 1,
        paddingVertical: 0,
        fontSize: 18,
        fontWeight: "800",
        letterSpacing: 0,
    },
        inlineSearchClear: {
        width: 28,
        height: 28,
        alignItems: "center",
        justifyContent: "center",
    },
        dropdownEmpty: {
        minHeight: 74,
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        paddingHorizontal: 18,
    },
        dropdownEmptyText: {
        fontSize: 14,
        fontWeight: "700",
        textAlign: "center",
    },
        searchResultList: {
        paddingTop: 8,
        paddingBottom: 8,
    },
        searchResultScroll: {
        maxHeight: 252,
    },
        searchResultRow: {
        minHeight: 58,
        marginHorizontal: 10,
        borderRadius: 16,
        borderBottomWidth: StyleSheet.hairlineWidth,
        paddingRight: 8,
        flexDirection: "row",
        alignItems: "center",
    },
        searchResultBar: {
        width: 4,
        height: 34,
        borderRadius: 2,
        marginLeft: 8,
    },
        searchResultBody: {
        flex: 1,
        paddingLeft: 10,
        paddingRight: 10,
    },
        searchResultTitle: {
        fontSize: 16,
        fontWeight: "800",
        letterSpacing: 0,
    },
        searchResultMeta: {
        marginTop: 3,
        fontSize: 12,
        fontWeight: "700",
        letterSpacing: 0,
    },
        searchResultTime: {
        minWidth: 68,
        textAlign: "right",
        fontSize: 12,
        fontWeight: "800",
        letterSpacing: 0,
    },
    });
}
