import { StyleSheet } from "react-native";

/** 네이티브 TMAP wrapper의 정적 스타일입니다. */
const nativeStyles = StyleSheet.create({
    container: { flex: 1 },
    fallback: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 16,
    },
    fallbackText: { textAlign: "center", fontSize: 12, lineHeight: 18 },
    loadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
    },
    loadingText: { fontSize: 12, lineHeight: 18, fontWeight: "700" },
    zoomControls: {
        position: "absolute",
        right: 12,
        top: "42%",
        width: 44,
        borderRadius: 12,
        backgroundColor: "rgba(255,255,255,0.96)",
        shadowColor: "#000000",
        shadowOpacity: 0.15,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
        elevation: 5,
        overflow: "hidden",
    },
    controlButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
    controlText: { color: "#111827", fontSize: 25, lineHeight: 29, fontWeight: "500" },
    controlDivider: { height: StyleSheet.hairlineWidth, backgroundColor: "#D1D5DB" },
    locationButton: {
        position: "absolute",
        right: 12,
        bottom: 18,
        width: 46,
        height: 46,
        borderRadius: 23,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(255,255,255,0.96)",
        shadowColor: "#000000",
        shadowOpacity: 0.15,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 3 },
        elevation: 5,
    },
    locationText: { color: "#2979FF", fontSize: 26, lineHeight: 30, fontWeight: "700" },
    errorOverlay: {
        position: "absolute",
        left: 12,
        right: 12,
        bottom: 12,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: "rgba(17, 24, 39, 0.86)",
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    errorCopy: { flex: 1, minWidth: 0 },
    errorTitle: { color: "#FFFFFF", fontWeight: "700", fontSize: 12, marginBottom: 4 },
    errorText: { color: "rgba(255,255,255,0.88)", fontSize: 11, lineHeight: 15 },
    retryButton: {
        minHeight: 36,
        borderRadius: 9,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#2979FF",
    },
    retryText: { color: "#FFFFFF", fontSize: 12, lineHeight: 16, fontWeight: "800" },
});

export default nativeStyles;
